mod ca;
mod connect;
mod gateway;
mod inject;
mod remote;
mod remote_api;
mod remote_mapping;
mod remote_store;

use std::path::{Path, PathBuf};

use anyhow::Result;
use clap::Parser;
use tracing::{info, warn};
use tracing_subscriber::EnvFilter;

use crate::ca::CertificateAuthority;
use crate::gateway::GatewayServer;
use crate::remote::{RemoteAccessConfig, RemoteAccessManager};

#[derive(Parser)]
#[command(
    name = "onecli-gateway",
    about = "OneCLI MITM gateway for credential injection"
)]
struct Cli {
    /// Port to listen on.
    #[arg(long, default_value = "10255")]
    port: u16,

    /// Data directory for CA certificates and persistent state.
    #[arg(long, default_value = default_data_dir())]
    data_dir: PathBuf,

    /// OneCLI web API base URL (for credential fetching).
    #[arg(long, default_value = "http://localhost:10254")]
    api_url: String,

    /// Path to the gateway–API shared secret file.
    /// The secret is used to authenticate credential requests to the web API.
    /// Can also be set via the GATEWAY_SECRET environment variable (takes precedence).
    #[arg(long, default_value = default_gateway_secret_file())]
    gateway_secret_file: PathBuf,

    /// Enable remote access (Bitwarden vault credential injection).
    #[arg(long, default_value = "false")]
    enable_remote_access: bool,

    /// WebSocket relay URL for remote access connections.
    #[arg(long, default_value = "wss://rat1.lesspassword.dev")]
    relay_url: String,
}

fn default_data_dir() -> &'static str {
    if cfg!(target_os = "linux") && Path::new("/app/data").exists() {
        "/app/data"
    } else {
        "~/.onecli"
    }
}

fn default_gateway_secret_file() -> &'static str {
    if cfg!(target_os = "linux") && Path::new("/app/data").exists() {
        "/app/data/gateway-secret"
    } else {
        "~/.onecli/gateway-secret"
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    // Install ring as the default rustls CryptoProvider (required by reqwest)
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("failed to install rustls CryptoProvider");

    // Initialize logging
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    let cli = Cli::parse();

    // Expand ~ in data dir
    let data_dir = expand_tilde(&cli.data_dir);

    info!(data_dir = %data_dir.display(), "starting onecli-gateway");

    // Load or generate CA
    let ca = CertificateAuthority::load_or_generate(&data_dir).await?;

    // Load gateway–API shared secret:
    // 1. GATEWAY_SECRET env var (cloud: injected from Secrets Manager)
    // 2. File on disk (OSS: generated by web API on startup)
    let gateway_secret = load_gateway_secret(&cli.gateway_secret_file);

    // Initialize remote access manager if enabled
    let remote_access = if cli.enable_remote_access {
        info!(relay_url = %cli.relay_url, "initializing remote access");
        let config = RemoteAccessConfig {
            relay_url: cli.relay_url,
        };
        match RemoteAccessManager::new(config, &data_dir) {
            Ok(manager) => {
                let manager = std::sync::Arc::new(manager);
                manager.try_restore_session().await;
                Some(manager)
            }
            Err(e) => {
                warn!(error = %e, "failed to initialize remote access — continuing without it");
                None
            }
        }
    } else {
        None
    };

    info!(
        port = cli.port,
        api_url = %cli.api_url,
        gateway_secret_loaded = gateway_secret.is_some(),
        remote_access_enabled = remote_access.is_some(),
        "gateway ready"
    );

    // Start the gateway server (blocks forever)
    let server = GatewayServer::new(ca, cli.port, cli.api_url, gateway_secret, remote_access);
    server.run().await
}

/// Load the gateway–API shared secret.
/// Checks `GATEWAY_SECRET` env var first (cloud), then reads from file (OSS).
/// Returns `None` if neither is available (credential fetching will be disabled).
fn load_gateway_secret(secret_file: &Path) -> Option<String> {
    // Cloud: env var takes precedence
    if let Ok(secret) = std::env::var("GATEWAY_SECRET") {
        let secret = secret.trim().to_string();
        if !secret.is_empty() {
            info!("loaded gateway secret from GATEWAY_SECRET env var");
            return Some(secret);
        }
    }

    // OSS: read from file
    let path = expand_tilde(secret_file);
    match std::fs::read_to_string(&path) {
        Ok(contents) => {
            let secret = contents.trim().to_string();
            if secret.is_empty() {
                warn!(path = %path.display(), "gateway secret file is empty");
                None
            } else {
                info!(path = %path.display(), "loaded gateway secret from file");
                Some(secret)
            }
        }
        Err(_) => {
            warn!(
                path = %path.display(),
                "gateway secret file not found — credential fetching will be unavailable until the web API generates it"
            );
            None
        }
    }
}

/// Expand `~` at the start of a path to the user's home directory.
fn expand_tilde(path: &Path) -> PathBuf {
    let s = path.to_string_lossy();
    if s.starts_with("~/") || s == "~" {
        if let Some(home) = std::env::var_os("HOME") {
            return PathBuf::from(home).join(s.strip_prefix("~/").unwrap_or(""));
        }
    }
    path.to_path_buf()
}
