import { NextResponse } from "next/server";
import { existsSync, readFileSync } from "fs";

const CA_PEM_FILE_DOCKER = "/app/data/proxy/ca.pem";
const CA_PEM_FILE_LOCAL = `${process.env.HOME}/.onecli/proxy/ca.pem`;

const isCloud = process.env.NEXT_PUBLIC_EDITION === "cloud";

const getCaPemFilePath = (): string => {
  if (process.env.PROXY_CA_PEM_FILE) return process.env.PROXY_CA_PEM_FILE;
  return existsSync("/app/data") ? CA_PEM_FILE_DOCKER : CA_PEM_FILE_LOCAL;
};

/**
 * Load the CA certificate PEM.
 * Cloud: from PROXY_CA_CERT env var. OSS: from file on disk.
 */
const loadCaPem = (): string | null => {
  // Cloud: env var
  const envCert = process.env.PROXY_CA_CERT?.trim();
  if (envCert) return envCert;

  if (isCloud) return null;

  // OSS: read from file (generated by the proxy on startup)
  const path = getCaPemFilePath();
  try {
    const pem = readFileSync(path, "utf-8").trim();
    return pem || null;
  } catch {
    return null;
  }
};

export async function GET() {
  const pem = loadCaPem();

  if (!pem) {
    return NextResponse.json(
      {
        error:
          "CA certificate not available. Start the proxy first to generate it.",
      },
      { status: 503 },
    );
  }

  return new NextResponse(pem, {
    status: 200,
    headers: {
      "content-type": "application/x-pem-file",
      "content-disposition": 'attachment; filename="onecli-proxy-ca.pem"',
    },
  });
}
