#!/bin/sh
set -eu

VAULT_BOOTSTRAP_DIR="${VAULT_BOOTSTRAP_DIR:-/vault/bootstrap}"
VAULT_TOKEN_FILE="${VAULT_TOKEN_FILE:-$VAULT_BOOTSTRAP_DIR/root_token}"

if [ -z "${VAULT_TOKEN:-}" ] && [ -f "$VAULT_TOKEN_FILE" ]; then
  # Trim trailing newlines from token files generated by shell tools.
  VAULT_TOKEN="$(tr -d '\r\n' < "$VAULT_TOKEN_FILE")"
  export VAULT_TOKEN
fi

if [ -z "${VAULT_TOKEN:-}" ]; then
  echo "VAULT_TOKEN is not set and token file was missing/empty at $VAULT_TOKEN_FILE"
  exit 1
fi

exec ./entrypoint.sh
