import { randomUUID } from "node:crypto";
import { db } from "@onecli/db";

/**
 * The org's AWS `sts:ExternalId` — the value a customer pins in their IAM
 * role's trust policy, and the one OneCLI must present when assuming it.
 *
 * AWS is explicit that the external ID has to be generated by the party doing
 * the assuming (us) and be unique per customer: it exists to defeat the
 * confused-deputy problem, where one customer induces us to assume a role with
 * an external ID belonging to another. That guarantee only holds while the
 * value is OURS — so it is minted here, server-side, from the caller's
 * authenticated organization, and is never accepted from request input.
 *
 * Minted lazily on first read and then stable forever: the id is what the
 * customer has already written into their trust policy, so re-minting it would
 * silently break every existing AWS Role connection in the org.
 *
 * Not a secret (AWS treats it as visible to anyone who can read the role), but
 * it IS org-scoped — an admin-gated read, never a public one.
 *
 * Shape: `onecli-<uuid4>` — 43 characters of AWS's permitted external-ID
 * alphabet (alphanumerics and `-`, well inside the 2..1224 bound), from a
 * CSPRNG so it is unguessable even though it need not be secret.
 *
 * Returns `""` for an organization that does not exist. Callers fail closed on
 * an empty value (the connect path refuses rather than assuming the role
 * without one, and the UI shows the field as unavailable), so an unresolvable
 * org can never silently become an AssumeRole with no external ID.
 */
export const ensureOrgAwsExternalId = async (
  organizationId: string,
): Promise<string> => {
  const org = await db.organization.findUnique({
    where: { id: organizationId },
    select: { awsExternalId: true },
  });
  if (!org) return "";
  if (org.awsExternalId) return org.awsExternalId;

  const externalId = `onecli-${randomUUID()}`;

  // Concurrent first-reads race here (two admins opening the connect popup at
  // once). `updateMany` with the "still unset" guard makes the write
  // conditional, so the loser's update matches no row and it re-reads the
  // winner's value instead of overwriting it — an overwrite would invalidate a
  // trust policy the customer may already have saved.
  const { count } = await db.organization.updateMany({
    where: { id: organizationId, awsExternalId: null },
    data: { awsExternalId: externalId },
  });
  if (count > 0) return externalId;

  const settled = await db.organization.findUnique({
    where: { id: organizationId },
    select: { awsExternalId: true },
  });
  return settled?.awsExternalId ?? externalId;
};
