import type { AppPermissionDefinition } from "./types";

export const affinityPermissions: AppPermissionDefinition = {
  provider: "affinity",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_persons",
          name: "List persons",
          description: "List and search person records",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/persons",
          method: "GET",
        },
        {
          id: "get_person",
          name: "Get person",
          description: "Retrieve a specific person record",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/persons/*",
          method: "GET",
        },
        {
          id: "list_companies",
          name: "List companies",
          description: "List and search company records",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/companies",
          method: "GET",
        },
        {
          id: "get_company",
          name: "Get company",
          description: "Retrieve a specific company record",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/companies/*",
          method: "GET",
        },
        {
          id: "list_opportunities",
          name: "List opportunities",
          description: "List and search deals/opportunities",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/opportunities",
          method: "GET",
        },
        {
          id: "list_lists",
          name: "List lists",
          description: "List all Affinity lists",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/lists",
          method: "GET",
        },
        {
          id: "list_notes",
          name: "List notes",
          description: "List notes on a record",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/notes",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_person",
          name: "Create person",
          description: "Create a new person record",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/persons",
          aliasPatterns: ["/persons"],
          method: "POST",
        },
        {
          id: "update_person",
          name: "Update person",
          description: "Update a person record",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/persons/*",
          method: "PATCH",
        },
        {
          id: "create_company",
          name: "Create company",
          description: "Create a new company record",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/companies",
          aliasPatterns: ["/organizations"],
          method: "POST",
        },
        {
          id: "create_note",
          name: "Create note",
          description: "Add a note to a record",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/notes",
          method: "POST",
        },
        {
          id: "create_list_entry",
          name: "Add to list",
          description: "Add an entry to an Affinity list",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/lists/*/list-entries",
          aliasPatterns: ["/lists/*/list-entries"],
          method: "POST",
        },
        {
          id: "delete_list_entry",
          name: "Remove from list",
          description: "Remove an entry from a list",
          hostPattern: "api.affinity.co",
          pathPattern: "/v2/lists/*/list-entries/*",
          aliasPatterns: ["/lists/*/list-entries/*"],
          method: "DELETE",
        },
        {
          id: "mcp",
          name: "MCP server",
          description:
            "Read or mutate via the Affinity MCP server (mcp.affinity.co, a single JSON-RPC endpoint).",
          hostPattern: "mcp.affinity.co",
          pathPattern: "/*",
        },
      ],
    },
  ],
};
