import type { AppPermissionDefinition } from "./types";

// Endpoints from Apollo's OpenAPI spec
// (https://docs.apollo.io/openapi/apollo-rest-api.json). Note Apollo uses
// POST for most searches, including read-only ones.
//
// `/x/*` is a prefix glob (any depth); `/x/*/` matches exactly one segment
// (slash-optional). The id lookups use the latter so they never widen into a
// record's sub-resources.
const HOST = "api.apollo.io";

export const apolloIoPermissions: AppPermissionDefinition = {
  provider: "apollo-io",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "search_people",
          name: "Search people",
          description: "Find prospects in Apollo's people database",
          hostPattern: HOST,
          pathPattern: "/api/v1/mixed_people/api_search",
          method: "POST",
        },
        {
          id: "enrich_person",
          name: "Enrich person",
          description:
            "Enrich one or more people, or fetch a person's full profile (uses Apollo credits)",
          hostPattern: HOST,
          pathPattern: "/api/v1/people/match",
          aliasPatterns: ["/api/v1/people/bulk_match", "/api/v1/people/*/"],
          methods: ["POST", "GET"],
        },
        {
          id: "search_companies",
          name: "Search companies",
          description: "Find companies in Apollo's database",
          hostPattern: HOST,
          pathPattern: "/api/v1/mixed_companies/search",
          method: "POST",
        },
        {
          id: "enrich_company",
          name: "Enrich company",
          description:
            "Enrich a company by domain, or fetch a company's full profile (uses Apollo credits)",
          hostPattern: HOST,
          pathPattern: "/api/v1/organizations/enrich",
          aliasPatterns: ["/api/v1/organizations/*/"],
          method: "GET",
        },
        {
          id: "bulk_enrich_companies",
          name: "Bulk enrich companies",
          description: "Enrich up to ten companies at once",
          hostPattern: HOST,
          pathPattern: "/api/v1/organizations/bulk_enrich",
          method: "POST",
        },
        {
          id: "get_company_job_postings",
          name: "Get company job postings",
          description: "List open job postings for a company",
          hostPattern: HOST,
          pathPattern: "/api/v1/organizations/*/job_postings",
          method: "GET",
        },
        {
          id: "search_contacts",
          name: "Search contacts",
          description: "Search contacts saved in your Apollo account",
          hostPattern: HOST,
          pathPattern: "/api/v1/contacts/search",
          method: "POST",
        },
        {
          id: "get_contact",
          name: "Get contact",
          description: "View a specific contact",
          hostPattern: HOST,
          pathPattern: "/api/v1/contacts/*/",
          method: "GET",
        },
        {
          id: "search_accounts",
          name: "Search accounts",
          description: "Search accounts saved in your Apollo account",
          hostPattern: HOST,
          pathPattern: "/api/v1/accounts/search",
          method: "POST",
        },
        {
          id: "get_account",
          name: "Get account",
          description: "View a specific account",
          hostPattern: HOST,
          pathPattern: "/api/v1/accounts/*/",
          method: "GET",
        },
        {
          id: "list_deals",
          name: "List deals",
          description: "List deals in your Apollo account",
          hostPattern: HOST,
          pathPattern: "/api/v1/opportunities/search",
          method: "GET",
        },
        {
          id: "get_deal",
          name: "Get deal",
          description: "View a specific deal",
          hostPattern: HOST,
          pathPattern: "/api/v1/opportunities/*/",
          method: "GET",
        },
        {
          id: "search_tasks",
          name: "Search tasks",
          description: "Search tasks in your Apollo account",
          hostPattern: HOST,
          pathPattern: "/api/v1/tasks/search",
          method: "POST",
        },
        {
          id: "get_task",
          name: "Get task",
          description: "View a specific task",
          hostPattern: HOST,
          pathPattern: "/api/v1/tasks/*/",
          method: "GET",
        },
        {
          id: "search_sequences",
          name: "Search sequences",
          description: "Search email sequences",
          hostPattern: HOST,
          pathPattern: "/api/v1/emailer_campaigns/search",
          method: "POST",
        },
        {
          id: "search_emails",
          name: "Search outreach emails",
          description: "Search emails sent through sequences",
          hostPattern: HOST,
          pathPattern: "/api/v1/emailer_messages/search",
          method: "GET",
        },
        {
          id: "list_email_accounts",
          name: "List email accounts",
          description: "List linked mailboxes",
          hostPattern: HOST,
          pathPattern: "/api/v1/email_accounts",
          method: "GET",
        },
        {
          id: "list_users",
          name: "List users",
          description: "List users in your Apollo team",
          hostPattern: HOST,
          pathPattern: "/api/v1/users/search",
          method: "GET",
        },
        {
          id: "get_profile",
          name: "Get profile",
          description: "View the connected user's profile",
          hostPattern: HOST,
          pathPattern: "/api/v1/users/api_profile",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_contact",
          name: "Create contact",
          description: "Add a new contact",
          hostPattern: HOST,
          pathPattern: "/api/v1/contacts",
          aliasPatterns: ["/api/v1/contacts/bulk_create"],
          method: "POST",
        },
        {
          id: "update_contact",
          name: "Update contact",
          description: "Update an existing contact",
          hostPattern: HOST,
          pathPattern: "/api/v1/contacts/*/",
          method: "PATCH",
        },
        {
          id: "bulk_update_contacts",
          name: "Bulk update contacts",
          description:
            "Update, restage, or reassign many contacts in one request",
          hostPattern: HOST,
          pathPattern: "/api/v1/contacts/bulk_update",
          aliasPatterns: [
            "/api/v1/contacts/update_stages",
            "/api/v1/contacts/update_owners",
          ],
          method: "POST",
        },
        {
          id: "create_account",
          name: "Create account",
          description: "Add a new account",
          hostPattern: HOST,
          pathPattern: "/api/v1/accounts",
          aliasPatterns: ["/api/v1/accounts/bulk_create"],
          method: "POST",
        },
        {
          id: "update_account",
          name: "Update account",
          description: "Update an existing account",
          hostPattern: HOST,
          pathPattern: "/api/v1/accounts/*/",
          method: "PATCH",
        },
        {
          id: "bulk_update_accounts",
          name: "Bulk update accounts",
          description: "Update or reassign many accounts in one request",
          hostPattern: HOST,
          pathPattern: "/api/v1/accounts/bulk_update",
          aliasPatterns: ["/api/v1/accounts/update_owners"],
          method: "POST",
        },
        {
          id: "create_deal",
          name: "Create deal",
          description: "Add a new deal",
          hostPattern: HOST,
          pathPattern: "/api/v1/opportunities",
          method: "POST",
        },
        {
          id: "update_deal",
          name: "Update deal",
          description: "Update an existing deal",
          hostPattern: HOST,
          pathPattern: "/api/v1/opportunities/*/",
          method: "PATCH",
        },
        {
          id: "create_task",
          name: "Create task",
          description: "Create one or more tasks",
          hostPattern: HOST,
          pathPattern: "/api/v1/tasks",
          aliasPatterns: ["/api/v1/tasks/bulk_create"],
          method: "POST",
        },
        {
          id: "update_task",
          name: "Update task",
          description: "Update an existing task",
          hostPattern: HOST,
          pathPattern: "/api/v1/tasks/*/",
          method: "PATCH",
        },
        {
          id: "complete_task",
          name: "Complete or skip task",
          description: "Mark a task complete or skip it",
          hostPattern: HOST,
          pathPattern: "/api/v1/tasks/*/complete",
          aliasPatterns: ["/api/v1/tasks/*/skip"],
          method: "POST",
        },
        {
          id: "add_to_sequence",
          name: "Add contacts to sequence",
          description: "Enroll contacts in an email sequence",
          hostPattern: HOST,
          pathPattern: "/api/v1/emailer_campaigns/*/add_contact_ids",
          method: "POST",
        },
      ],
    },
  ],
};
