import type { AppPermissionDefinition } from "./types";

export const attioPermissions: AppPermissionDefinition = {
  provider: "attio",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_records",
          name: "List records",
          description: "Query contacts, companies, and deals",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/objects/*/records/query",
          method: "POST",
        },
        {
          id: "get_record",
          name: "Get record",
          description: "Retrieve a specific record",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/objects/*/records/*",
          method: "GET",
        },
        {
          id: "list_objects",
          name: "List objects",
          description: "List all objects and their configuration",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/objects",
          method: "GET",
        },
        {
          id: "get_object",
          name: "Get object",
          description: "Retrieve a specific object configuration",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/objects/*",
          method: "GET",
        },
        {
          id: "list_lists",
          name: "List lists",
          description: "List all lists",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/lists",
          method: "GET",
        },
        {
          id: "get_list",
          name: "Get list",
          description: "Retrieve a specific list",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/lists/*",
          method: "GET",
        },
        {
          id: "list_entries",
          name: "List entries",
          description: "Query entries in a list",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/lists/*/entries/query",
          method: "POST",
        },
        {
          id: "list_notes",
          name: "List notes",
          description: "List notes on a record",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/notes",
          method: "GET",
        },
        {
          id: "get_note",
          name: "Get note",
          description: "Retrieve a specific note",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/notes/*",
          method: "GET",
        },
        {
          id: "list_tasks",
          name: "List tasks",
          description: "List tasks",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/tasks",
          method: "GET",
        },
        {
          id: "get_task",
          name: "Get task",
          description: "Retrieve a specific task",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/tasks/*",
          method: "GET",
        },
        {
          id: "list_comments",
          name: "List comments",
          description: "List comments in a thread",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/threads/*/comments",
          method: "GET",
        },
        {
          id: "list_workspace_members",
          name: "List workspace members",
          description: "View workspace members",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/workspace_members",
          method: "GET",
        },
        {
          id: "get_workspace_member",
          name: "Get workspace member",
          description: "Retrieve a specific workspace member",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/workspace_members/*",
          method: "GET",
        },
        {
          id: "list_webhooks",
          name: "List webhooks",
          description: "List registered webhooks",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/webhooks",
          method: "GET",
        },
        {
          id: "get_webhook",
          name: "Get webhook",
          description: "Retrieve a specific webhook",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/webhooks/*",
          method: "GET",
        },
        {
          id: "self",
          name: "Self",
          description: "View token and workspace info",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/self",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_record",
          name: "Create record",
          description: "Create a new contact, company, or deal",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/objects/*/records",
          method: "POST",
        },
        {
          id: "update_record",
          name: "Update record",
          description: "Update an existing record",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/objects/*/records/*",
          method: "PATCH",
        },
        {
          id: "delete_record",
          name: "Delete record",
          description: "Delete a record",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/objects/*/records/*",
          method: "DELETE",
        },
        {
          id: "create_list_entry",
          name: "Create list entry",
          description: "Add an entry to a list",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/lists/*/entries",
          method: "POST",
        },
        {
          id: "update_list_entry",
          name: "Update list entry",
          description: "Update a list entry",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/lists/*/entries/*",
          method: "PATCH",
        },
        {
          id: "delete_list_entry",
          name: "Delete list entry",
          description: "Remove an entry from a list",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/lists/*/entries/*",
          method: "DELETE",
        },
        {
          id: "create_note",
          name: "Create note",
          description: "Create a note on a record",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/notes",
          method: "POST",
        },
        {
          id: "delete_note",
          name: "Delete note",
          description: "Delete a note",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/notes/*",
          method: "DELETE",
        },
        {
          id: "create_task",
          name: "Create task",
          description: "Create a new task",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/tasks",
          method: "POST",
        },
        {
          id: "update_task",
          name: "Update task",
          description: "Update a task",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/tasks/*",
          method: "PATCH",
        },
        {
          id: "delete_task",
          name: "Delete task",
          description: "Delete a task",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/tasks/*",
          method: "DELETE",
        },
        {
          id: "create_comment",
          name: "Create comment",
          description: "Post a comment to a thread",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/threads/*/comments",
          method: "POST",
        },
        {
          id: "create_webhook",
          name: "Create webhook",
          description: "Register a new webhook",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/webhooks",
          method: "POST",
        },
        {
          id: "update_webhook",
          name: "Update webhook",
          description: "Update a webhook",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/webhooks/*",
          method: "PATCH",
        },
        {
          id: "delete_webhook",
          name: "Delete webhook",
          description: "Delete a webhook",
          hostPattern: "api.attio.com",
          pathPattern: "/v2/webhooks/*",
          method: "DELETE",
        },
      ],
    },
  ],
};
