import type { AppPermissionDefinition } from "./types";

export const datadogPermissions: AppPermissionDefinition = {
  provider: "datadog",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "dashboards_list",
          name: "List dashboards",
          description: "List all dashboards in the organization",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/dashboard",
          method: "GET",
        },
        {
          id: "dashboards_get",
          name: "Get dashboard",
          description: "Get a specific dashboard by ID",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/dashboard/*",
          method: "GET",
        },
        {
          id: "monitors_list",
          name: "List monitors",
          description: "List all monitors in the organization",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/monitor",
          method: "GET",
        },
        {
          id: "monitors_get",
          name: "Get monitor",
          description: "Get a specific monitor by ID",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/monitor/*",
          method: "GET",
        },
        {
          id: "logs_search",
          name: "Search logs",
          description: "Search and list log events",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v2/logs/*",
          method: "POST",
        },
        {
          id: "logs_config_read",
          name: "Read logs configuration",
          description: "List log archives, indexes, and pipelines",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v2/logs/*",
          method: "GET",
        },
        {
          id: "metrics_query",
          name: "Query metrics",
          description: "Query time-series metrics data",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/query",
          method: "GET",
        },
        {
          id: "metrics_list",
          name: "List metrics",
          description: "List available metrics",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/metrics",
          method: "GET",
        },
        {
          id: "events_list",
          name: "List events",
          description: "List events from the event stream",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/events",
          method: "GET",
        },
        {
          id: "hosts_list",
          name: "List hosts",
          description: "List infrastructure hosts",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/hosts",
          method: "GET",
        },
        {
          id: "apm_services",
          name: "List APM services",
          description: "List APM services and traces",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/service_dependencies",
          method: "GET",
        },
        {
          id: "slos_list",
          name: "List SLOs",
          description: "List service level objectives",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/slo",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "logs_submit",
          name: "Submit logs",
          description: "Send log entries to Datadog",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v2/logs",
          method: "POST",
        },
        {
          id: "monitors_create",
          name: "Create monitor",
          description: "Create a new monitor",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/monitor",
          method: "POST",
        },
        {
          id: "monitors_update",
          name: "Update monitor",
          description: "Update an existing monitor",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/monitor/*",
          method: "PUT",
        },
        {
          id: "monitors_delete",
          name: "Delete monitor",
          description: "Delete a monitor",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/monitor/*",
          method: "DELETE",
        },
        {
          id: "dashboards_create",
          name: "Create dashboard",
          description: "Create a new dashboard",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/dashboard",
          method: "POST",
        },
        {
          id: "dashboards_update",
          name: "Update dashboard",
          description: "Update an existing dashboard",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/dashboard/*",
          method: "PUT",
        },
        {
          id: "dashboards_delete",
          name: "Delete dashboard",
          description: "Delete a dashboard",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/dashboard/*",
          method: "DELETE",
        },
        {
          id: "events_post",
          name: "Post event",
          description: "Post an event to the event stream",
          hostPattern: "*.datadoghq.com",
          pathPattern: "/api/v1/events",
          method: "POST",
        },
      ],
    },
  ],
};
