import type { AppPermissionDefinition } from "./types";

export const googleChatPermissions: AppPermissionDefinition = {
  provider: "google-chat",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_spaces",
          name: "List spaces",
          description: "List Chat spaces the user is a member of",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces",
          method: "GET",
        },
        {
          id: "get_space",
          name: "Get space",
          description: "Retrieve details of a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*",
          method: "GET",
        },
        {
          id: "list_members",
          name: "List members",
          description: "List members of a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/members",
          method: "GET",
        },
        {
          id: "list_messages",
          name: "List messages",
          description: "List messages in a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/messages",
          method: "GET",
        },
        {
          id: "get_message",
          name: "Get message",
          description: "Retrieve a specific message",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/messages/*",
          method: "GET",
        },
        {
          id: "get_member",
          name: "Get member",
          description: "Retrieve a specific member of a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/members/*",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_space",
          name: "Create space",
          description: "Create a new Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces",
          method: "POST",
        },
        {
          id: "update_space",
          name: "Update space",
          description: "Update a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*",
          method: "PATCH",
        },
        {
          id: "delete_space",
          name: "Delete space",
          description: "Delete a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*",
          method: "DELETE",
        },
        {
          id: "create_message",
          name: "Send message",
          description: "Send a message to a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/messages",
          method: "POST",
        },
        {
          id: "update_message",
          name: "Update message",
          description: "Update a message in a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/messages/*",
          method: "PATCH",
        },
        {
          id: "delete_message",
          name: "Delete message",
          description: "Delete a message from a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/messages/*",
          method: "DELETE",
        },
        {
          id: "create_member",
          name: "Add member",
          description: "Add a member to a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/members",
          method: "POST",
        },
        {
          id: "delete_member",
          name: "Remove member",
          description: "Remove a member from a Chat space",
          hostPattern: "chat.googleapis.com",
          pathPattern: "/v1/spaces/*/members/*",
          method: "DELETE",
        },
      ],
    },
  ],
};
