import type { AppPermissionDefinition } from "./types";

export const hubspotPermissions: AppPermissionDefinition = {
  provider: "hubspot",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_contacts",
          name: "List contacts",
          description: "List CRM contacts",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/contacts",
          method: "GET",
        },
        {
          id: "get_contact",
          name: "Get contact",
          description: "Retrieve a specific contact",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/contacts/*",
          method: "GET",
        },
        {
          id: "list_companies",
          name: "List companies",
          description: "List CRM companies",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/companies",
          method: "GET",
        },
        {
          id: "get_company",
          name: "Get company",
          description: "Retrieve a specific company",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/companies/*",
          method: "GET",
        },
        {
          id: "list_deals",
          name: "List deals",
          description: "List CRM deals",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/deals",
          method: "GET",
        },
        {
          id: "get_deal",
          name: "Get deal",
          description: "Retrieve a specific deal",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/deals/*",
          method: "GET",
        },
        {
          id: "search_crm",
          name: "Search CRM",
          description: "Search across CRM objects",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/*/search",
          method: "POST",
        },
        {
          id: "list_tickets",
          name: "List tickets",
          description: "List CRM tickets",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/tickets",
          method: "GET",
        },
        {
          id: "get_ticket",
          name: "Get ticket",
          description: "Retrieve a specific ticket",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/tickets/*",
          method: "GET",
        },
        {
          id: "list_owners",
          name: "List owners",
          description: "List record owners",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/owners",
          method: "GET",
        },
        {
          id: "list_associations",
          name: "List associations",
          description: "List associations between CRM objects",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v4/objects/*/*/associations/*",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_contact",
          name: "Create contact",
          description: "Create a new contact",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/contacts",
          method: "POST",
        },
        {
          id: "update_contact",
          name: "Update contact",
          description: "Update an existing contact",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/contacts/*",
          method: "PATCH",
        },
        {
          id: "create_company",
          name: "Create company",
          description: "Create a new company",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/companies",
          method: "POST",
        },
        {
          id: "update_company",
          name: "Update company",
          description: "Update an existing company",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/companies/*",
          method: "PATCH",
        },
        {
          id: "create_deal",
          name: "Create deal",
          description: "Create a new deal",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/deals",
          method: "POST",
        },
        {
          id: "update_deal",
          name: "Update deal",
          description: "Update an existing deal",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/deals/*",
          method: "PATCH",
        },
        {
          id: "create_ticket",
          name: "Create ticket",
          description: "Create a new ticket",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/tickets",
          method: "POST",
        },
        {
          id: "update_ticket",
          name: "Update ticket",
          description: "Update an existing ticket",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v3/objects/tickets/*",
          method: "PATCH",
        },
        {
          id: "create_association",
          name: "Create association",
          description: "Associate two CRM objects",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v4/objects/*/*/associations/*",
          method: "PUT",
        },
        {
          id: "delete_association",
          name: "Delete association",
          description: "Remove an association between CRM objects",
          hostPattern: "api.hubapi.com",
          pathPattern: "/crm/v4/objects/*/*/associations/*",
          method: "DELETE",
        },
      ],
    },
  ],
};
