import type { AppPermissionDefinition } from "./types";

export const microsoft365Permissions: AppPermissionDefinition = {
  provider: "microsoft-365",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "get_profile",
          name: "Read profile",
          description: "Read the signed-in user's profile",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me",
          method: "GET",
        },
        {
          id: "list_messages",
          name: "List email messages",
          description: "List messages in the mailbox",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/messages",
          aliasPatterns: ["/v1.0/users/*/messages"],
          method: "GET",
        },
        {
          id: "get_message",
          name: "Read email message",
          description: "Retrieve a specific email message",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/messages/*",
          aliasPatterns: ["/v1.0/users/*/messages/*"],
          method: "GET",
        },
        {
          id: "list_mail_folders",
          name: "List mail folders",
          description: "List mail folders in the mailbox",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/mailFolders",
          aliasPatterns: ["/v1.0/users/*/mailFolders"],
          method: "GET",
        },
        {
          id: "list_folder_messages",
          name: "List folder messages",
          description: "List messages in a specific mail folder",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/mailFolders/*/messages",
          aliasPatterns: ["/v1.0/users/*/mailFolders/*/messages"],
          method: "GET",
        },
        {
          id: "list_events",
          name: "List calendar events",
          description: "List events on the user's calendar",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/events",
          aliasPatterns: ["/v1.0/users/*/events"],
          method: "GET",
        },
        {
          id: "get_event",
          name: "Read calendar event",
          description: "Retrieve a specific calendar event",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/events/*",
          aliasPatterns: ["/v1.0/users/*/events/*"],
          method: "GET",
        },
        {
          id: "get_calendar_view",
          name: "View calendar range",
          description: "List events within a date range",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/calendarView",
          aliasPatterns: ["/v1.0/users/*/calendarView"],
          method: "GET",
        },
        {
          id: "list_calendars",
          name: "List calendars",
          description: "List the user's calendars",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/calendars",
          aliasPatterns: ["/v1.0/users/*/calendars"],
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "send_mail",
          name: "Send email",
          description: "Send an email message",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/sendMail",
          aliasPatterns: ["/v1.0/users/*/sendMail"],
          method: "POST",
        },
        {
          id: "create_draft",
          name: "Create draft",
          description: "Create a draft email message",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/messages",
          aliasPatterns: ["/v1.0/users/*/messages"],
          method: "POST",
        },
        {
          id: "update_message",
          name: "Update email message",
          description: "Update a message (flags, read state, drafts)",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/messages/*",
          aliasPatterns: ["/v1.0/users/*/messages/*"],
          method: "PATCH",
        },
        {
          id: "delete_message",
          name: "Delete email message",
          description: "Delete an email message",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/messages/*",
          aliasPatterns: ["/v1.0/users/*/messages/*"],
          method: "DELETE",
        },
        {
          id: "move_message",
          name: "Move email message",
          description: "Move a message to another folder",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/messages/*/move",
          aliasPatterns: ["/v1.0/users/*/messages/*/move"],
          method: "POST",
        },
        {
          id: "reply_message",
          name: "Reply to email",
          description: "Reply to the sender of a message",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/messages/*/reply",
          aliasPatterns: ["/v1.0/users/*/messages/*/reply"],
          method: "POST",
        },
        {
          id: "reply_all_message",
          name: "Reply all to email",
          description: "Reply to all recipients of a message",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/messages/*/replyAll",
          aliasPatterns: ["/v1.0/users/*/messages/*/replyAll"],
          method: "POST",
        },
        {
          id: "create_event",
          name: "Create calendar event",
          description: "Create a new calendar event",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/events",
          aliasPatterns: ["/v1.0/users/*/events"],
          method: "POST",
        },
        {
          id: "update_event",
          name: "Update calendar event",
          description: "Modify an existing calendar event",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/events/*",
          aliasPatterns: ["/v1.0/users/*/events/*"],
          method: "PATCH",
        },
        {
          id: "delete_event",
          name: "Delete calendar event",
          description: "Delete a calendar event",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/events/*",
          aliasPatterns: ["/v1.0/users/*/events/*"],
          method: "DELETE",
        },
        {
          id: "accept_event",
          name: "Accept invitation",
          description: "Accept a meeting invitation",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/events/*/accept",
          aliasPatterns: ["/v1.0/users/*/events/*/accept"],
          method: "POST",
        },
        {
          id: "decline_event",
          name: "Decline invitation",
          description: "Decline a meeting invitation",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/events/*/decline",
          aliasPatterns: ["/v1.0/users/*/events/*/decline"],
          method: "POST",
        },
        {
          id: "tentatively_accept_event",
          name: "Tentatively accept invitation",
          description: "Tentatively accept a meeting invitation",
          hostPattern: "graph.microsoft.com",
          pathPattern: "/v1.0/me/events/*/tentativelyAccept",
          aliasPatterns: ["/v1.0/users/*/events/*/tentativelyAccept"],
          method: "POST",
        },
      ],
    },
  ],
};
