import type { AppPermissionDefinition, AppTool } from "./types";

// Pylon REST API (docs.usepylon.com/pylon-docs/developer/api/api-reference),
// every path from the OpenAPI the reference pages embed. The same API is
// served from two regional hosts, so every tool answers on both: the gateway
// routes a connection to its own region (see the gateway host rewrite).
//
// Single-item paths end in `*/`: one segment exactly (with or without the
// trailing slash), never deeper. `/issues/*` would also match
// `/issues/{id}/messages`, so "Get issue" would leak the message history and
// "Delete issue" would answer the followers route.
//
// Pylon's `POST /{resource}/search` endpoints are READS (a filter in the
// body), so they are read tools; the separation between read and write is a
// question of path, not method. The hosted MCP server at mcp.usepylon.com
// authenticates with its own OAuth, not the API token, so it is not cataloged.
const HOST = "api.usepylon.com";
const HOST_ALIASES = ["api.eu.usepylon.com"];

const read = (
  id: string,
  name: string,
  description: string,
  pathPattern: string,
  method: "GET" | "POST" = "GET",
): AppTool => ({
  id,
  name,
  description,
  hostPattern: HOST,
  hostAliasPatterns: HOST_ALIASES,
  pathPattern,
  method,
});

const write = (
  id: string,
  name: string,
  description: string,
  pathPattern: string,
  methods: string[],
  aliasPatterns?: string[],
): AppTool => ({
  id,
  name,
  description,
  hostPattern: HOST,
  hostAliasPatterns: HOST_ALIASES,
  pathPattern,
  ...(aliasPatterns ? { aliasPatterns } : {}),
  ...(methods.length === 1 ? { method: methods[0] } : { methods }),
});

export const pylonPermissions: AppPermissionDefinition = {
  provider: "pylon",
  groups: [
    {
      category: "read",
      tools: [
        read(
          "get_me",
          "Get organization",
          "View the organization and user behind the token",
          "/me",
        ),
        // Issues
        read(
          "list_issues",
          "List issues",
          "List issues in a time range",
          "/issues",
        ),
        read(
          "search_issues",
          "Search issues",
          "Search issues by a filter",
          "/issues/search",
          "POST",
        ),
        read(
          "get_issue",
          "Get issue",
          "Read an issue by its ID or number",
          "/issues/*/",
        ),
        read(
          "get_issue_messages",
          "Get issue messages",
          "Read the messages and threads on an issue",
          "/issues/*/messages",
        ),
        read(
          "get_issue_threads",
          "Get issue threads",
          "Read the internal threads on an issue",
          "/issues/*/threads",
        ),
        read(
          "get_issue_followers",
          "Get issue followers",
          "View who follows an issue",
          "/issues/*/followers",
        ),
        read(
          "get_issue_voice_calls",
          "Get issue voice calls",
          "Read the voice calls, recordings, and transcripts on an issue",
          "/issues/*/voice-calls",
        ),
        read(
          "list_issue_statuses",
          "List issue statuses",
          "View the default and custom issue statuses",
          "/issue-statuses",
        ),
        // Accounts
        read(
          "list_accounts",
          "List accounts",
          "List customer accounts",
          "/accounts",
        ),
        read(
          "search_accounts",
          "Search accounts",
          "Search accounts by a filter",
          "/accounts/search",
          "POST",
        ),
        read(
          "get_account",
          "Get account",
          "Read an account by its ID or external ID",
          "/accounts/*/",
        ),
        read(
          "get_account_relationships",
          "Get account relationships",
          "View an account's relationships to other accounts",
          "/accounts/*/relationships",
        ),
        read(
          "get_account_activities",
          "Get account activities",
          "Read the custom activities logged on an account",
          "/accounts/*/activities",
        ),
        read(
          "get_account_notebook_notes",
          "Get account notebook notes",
          "Read the notes in an account notebook block",
          "/accounts/*/notebook-blocks/*/notes",
        ),
        read(
          "list_activity_types",
          "List activity types",
          "View the custom activity types",
          "/activity-types",
        ),
        // Contacts
        read("list_contacts", "List contacts", "List contacts", "/contacts"),
        read(
          "search_contacts",
          "Search contacts",
          "Search contacts by a filter",
          "/contacts/search",
          "POST",
        ),
        read(
          "get_contact",
          "Get contact",
          "Read a contact by its ID or external ID",
          "/contacts/*/",
        ),
        // Users and teams
        read("list_users", "List users", "List the team's users", "/users"),
        read(
          "search_users",
          "Search users",
          "Search users by a filter",
          "/users/search",
          "POST",
        ),
        read("get_user", "Get user", "Read a user by its ID", "/users/*/"),
        read(
          "list_user_roles",
          "List user roles",
          "View the user roles",
          "/user-roles",
        ),
        read("list_teams", "List teams", "List teams", "/teams"),
        read("get_team", "Get team", "Read a team by its ID", "/teams/*/"),
        // Knowledge base
        read(
          "list_knowledge_bases",
          "List knowledge bases",
          "List the knowledge bases",
          "/knowledge-bases",
        ),
        read(
          "get_knowledge_base",
          "Get knowledge base",
          "Read a knowledge base by its ID",
          "/knowledge-bases/*/",
        ),
        read(
          "list_collections",
          "List collections",
          "List the collections in a knowledge base",
          "/knowledge-bases/*/collections",
        ),
        read(
          "get_collection",
          "Get collection",
          "Read a collection by its ID",
          "/knowledge-bases/*/collections/*/",
        ),
        read(
          "list_articles",
          "List articles",
          "List the articles in a knowledge base",
          "/knowledge-bases/*/articles",
        ),
        read(
          "get_article",
          "Get article",
          "Read an article's content and settings",
          "/knowledge-bases/*/articles/*/",
        ),
        read(
          "get_knowledge_base_theme",
          "Get knowledge base theme",
          "Read a knowledge base theme",
          "/knowledge-bases/*/themes/*/",
        ),
        read(
          "list_article_feedback",
          "List article feedback",
          "Read the feedback left on articles",
          "/article-feedback",
        ),
        // Tasks, projects, milestones
        read("list_tasks", "List tasks", "List tasks", "/tasks"),
        read(
          "search_tasks",
          "Search tasks",
          "Search tasks by a filter",
          "/tasks/search",
          "POST",
        ),
        read("get_task", "Get task", "Read a task by its ID", "/tasks/*/"),
        read(
          "get_task_comments",
          "Get task comments",
          "Read the comments on a task",
          "/tasks/*/comments",
        ),
        read(
          "search_projects",
          "Search projects",
          "Search projects by a filter",
          "/projects/search",
          "POST",
        ),
        read(
          "get_project",
          "Get project",
          "Read a project by its ID",
          "/projects/*/",
        ),
        read(
          "search_milestones",
          "Search milestones",
          "Search milestones by a filter",
          "/milestones/search",
          "POST",
        ),
        read(
          "get_milestone",
          "Get milestone",
          "Read a milestone by its ID",
          "/milestones/*/",
        ),
        // Feature requests
        read(
          "search_feature_requests",
          "Search feature requests",
          "Search or list feature requests",
          "/feature-requests/search",
          "POST",
        ),
        read(
          "get_feature_request",
          "Get feature request",
          "Read a feature request by its ID",
          "/feature-requests/*/",
        ),
        // Call recordings
        read(
          "search_call_recordings",
          "Search call recordings",
          "Search call recordings by a filter",
          "/call-recordings/search",
          "POST",
        ),
        read(
          "get_call_recording",
          "Get call recording",
          "Read a call recording by its ID",
          "/call-recordings/*/",
        ),
        // Custom fields and objects
        read(
          "list_custom_fields",
          "List custom fields",
          "View the custom field definitions",
          "/custom-fields",
        ),
        read(
          "get_custom_field",
          "Get custom field",
          "Read a custom field by its ID",
          "/custom-fields/*/",
        ),
        read(
          "list_custom_objects",
          "List custom objects",
          "List the custom objects of a type",
          "/custom-objects/*/",
        ),
        read(
          "search_custom_objects",
          "Search custom objects",
          "Search custom objects by a filter",
          "/custom-objects/*/search",
          "POST",
        ),
        read(
          "get_custom_object",
          "Get custom object",
          "Read a custom object by its ID",
          "/custom-objects/*/*/",
        ),
        // Tags, macros, surveys, ticket forms
        read("list_tags", "List tags", "View the tags", "/tags"),
        read("get_tag", "Get tag", "Read a tag by its ID", "/tags/*/"),
        read("list_macros", "List macros", "View the macros", "/macros"),
        read("get_macro", "Get macro", "Read a macro by its ID", "/macros/*/"),
        read(
          "list_macro_groups",
          "List macro groups",
          "View the macro groups",
          "/macro-groups",
        ),
        read("list_surveys", "List surveys", "List surveys", "/surveys"),
        read(
          "search_surveys",
          "Search surveys",
          "Search surveys by a filter",
          "/surveys/search",
          "POST",
        ),
        read(
          "get_survey",
          "Get survey",
          "Read a survey by its ID",
          "/surveys/*/",
        ),
        read(
          "get_survey_responses",
          "Get survey responses",
          "Read the responses to a survey",
          "/surveys/*/responses",
        ),
        read(
          "list_ticket_forms",
          "List ticket forms",
          "List the ticket forms",
          "/ticket-forms",
        ),
        read(
          "get_ticket_form",
          "Get ticket form",
          "Read a ticket form by its ID",
          "/ticket-forms/*/",
        ),
        // Email, training data, audit logs
        read(
          "list_email_suppressions",
          "List email suppressions",
          "View the suppressed email recipients",
          "/email-suppressions",
        ),
        read(
          "list_training_data",
          "List training data",
          "List the AI training data configurations",
          "/training-data",
        ),
        read(
          "get_training_data",
          "Get training data",
          "Read a training data configuration by its ID",
          "/training-data/*/",
        ),
        read(
          "list_audit_logs",
          "List audit logs",
          "Read the audit log",
          "/audit-logs",
        ),
        read(
          "search_audit_logs",
          "Search audit logs",
          "Search the audit log by a filter",
          "/audit-logs/search",
          "POST",
        ),
      ],
    },
    {
      category: "write",
      tools: [
        // Issues
        write("create_issue", "Create issue", "Open a new issue", "/issues", [
          "POST",
        ]),
        write(
          "update_issue",
          "Update issue",
          "Change an issue's title, state, assignee, tags, or fields",
          "/issues/*/",
          ["PATCH"],
        ),
        write("delete_issue", "Delete issue", "Delete an issue", "/issues/*/", [
          "DELETE",
        ]),
        write(
          "snooze_issue",
          "Snooze issue",
          "Snooze an issue until a later time",
          "/issues/*/snooze",
          ["POST"],
        ),
        write(
          "manage_issue_followers",
          "Manage issue followers",
          "Add or remove followers on an issue",
          "/issues/*/followers",
          ["POST"],
        ),
        write(
          "link_external_issue",
          "Link external issue",
          "Link or unlink an external ticket to an issue",
          "/issues/*/external-issues",
          ["POST"],
        ),
        write(
          "create_issue_ai_response",
          "Create AI response",
          "Generate an AI response for an issue",
          "/issues/*/ai-response",
          ["POST"],
        ),
        write(
          "manage_issue_groups",
          "Manage issue groups",
          "Create an issue group or change its children",
          "/issue-groups",
          ["POST", "DELETE"],
          ["/issue-groups/*/children", "/issue-groups/*/children/*/"],
        ),
        // Messages
        write(
          "reply_to_issue",
          "Reply to issue",
          "Send a customer-facing reply on an issue",
          "/issues/*/reply",
          ["POST"],
        ),
        write(
          "draft_issue_reply",
          "Draft issue reply",
          "Create or update a draft reply on an issue",
          "/issues/*/draft-reply",
          ["POST"],
        ),
        write(
          "create_issue_note",
          "Create internal note",
          "Post an internal note on an issue",
          "/issues/*/note",
          ["POST"],
        ),
        write(
          "create_issue_thread",
          "Create issue thread",
          "Start an internal thread on an issue",
          "/issues/*/threads",
          ["POST"],
        ),
        write(
          "redact_message",
          "Redact message",
          "Redact the content of a message",
          "/issues/*/messages/*/redact",
          ["POST"],
        ),
        write(
          "delete_message",
          "Delete message",
          "Delete a message from an issue",
          "/issues/*/messages/*/",
          ["DELETE"],
        ),
        // Accounts
        write(
          "create_account",
          "Create account",
          "Create a customer account",
          "/accounts",
          ["POST"],
        ),
        write(
          "update_account",
          "Update account",
          "Change an account's name, domains, owner, tags, or fields",
          "/accounts/*/",
          ["PATCH"],
        ),
        write(
          "update_accounts",
          "Update multiple accounts",
          "Change several accounts at once",
          "/accounts",
          ["PATCH"],
        ),
        write(
          "delete_account",
          "Delete account",
          "Delete an account",
          "/accounts/*/",
          ["DELETE"],
        ),
        write(
          "merge_accounts",
          "Merge accounts",
          "Merge accounts into one",
          "/accounts/merge",
          ["POST"],
        ),
        write(
          "manage_account_relationships",
          "Manage account relationships",
          "Create or delete a relationship between accounts",
          "/accounts/*/relationship",
          ["POST", "DELETE"],
          ["/accounts/*/relationships/*/"],
        ),
        write(
          "create_account_activity",
          "Create account activity",
          "Log a custom activity on an account",
          "/accounts/*/activities",
          ["POST"],
        ),
        write(
          "create_account_notebook_note",
          "Create account notebook note",
          "Append a note to an account notebook block",
          "/accounts/*/notebook-blocks/*/notes",
          ["POST"],
        ),
        // Contacts
        write(
          "create_contact",
          "Create contact",
          "Create a contact",
          "/contacts",
          ["POST"],
        ),
        write(
          "update_contact",
          "Update contact",
          "Change a contact's details",
          "/contacts/*/",
          ["PATCH"],
        ),
        write(
          "delete_contact",
          "Delete contact",
          "Delete a contact",
          "/contacts/*/",
          ["DELETE"],
        ),
        // Users and teams
        write(
          "update_user",
          "Update user",
          "Change a user's details or role",
          "/users/*/",
          ["PATCH"],
        ),
        write("create_team", "Create team", "Create a team", "/teams", [
          "POST",
        ]),
        write(
          "update_team",
          "Update team",
          "Change a team's details or members",
          "/teams/*/",
          ["PATCH"],
        ),
        // Knowledge base
        write(
          "create_article",
          "Create article",
          "Create a knowledge base article",
          "/knowledge-bases/*/articles",
          ["POST"],
        ),
        write(
          "update_article",
          "Update article",
          "Change an article's content, settings, or publish state",
          "/knowledge-bases/*/articles/*/",
          ["PATCH"],
        ),
        write(
          "delete_article",
          "Delete article",
          "Delete a knowledge base article",
          "/knowledge-bases/*/articles/*/",
          ["DELETE"],
        ),
        write(
          "request_article_review",
          "Request article review",
          "Request a review on an article",
          "/knowledge-bases/*/articles/*/request-review",
          ["POST"],
        ),
        write(
          "create_collection",
          "Create collection",
          "Create a knowledge base collection",
          "/knowledge-bases/*/collections",
          ["POST"],
        ),
        write(
          "update_collection",
          "Update collection",
          "Change a collection's details",
          "/knowledge-bases/*/collections/*/",
          ["PATCH"],
        ),
        write(
          "delete_collection",
          "Delete collection",
          "Delete a knowledge base collection",
          "/knowledge-bases/*/collections/*/",
          ["DELETE"],
        ),
        write(
          "manage_knowledge_base_theme",
          "Manage knowledge base theme",
          "Edit a knowledge base theme draft or publish it",
          "/knowledge-bases/*/themes/*/",
          ["PATCH", "POST"],
          ["/knowledge-bases/*/themes/*/publish"],
        ),
        write(
          "create_route_redirect",
          "Create route redirect",
          "Add a URL redirect to a knowledge base",
          "/knowledge-bases/*/route-redirects",
          ["POST"],
        ),
        // Tasks, projects, milestones
        write("create_task", "Create task", "Create a task", "/tasks", [
          "POST",
        ]),
        write(
          "update_task",
          "Update task",
          "Change a task's details or status",
          "/tasks/*/",
          ["PATCH"],
        ),
        write("delete_task", "Delete task", "Delete a task", "/tasks/*/", [
          "DELETE",
        ]),
        write(
          "link_task_issue",
          "Link task to issue",
          "Link or unlink a Pylon issue or external ticket to a task",
          "/tasks/*/issues",
          ["POST"],
          ["/tasks/*/external-issues"],
        ),
        write(
          "manage_task_comments",
          "Manage task comments",
          "Add, edit, or delete comments on a task",
          "/tasks/*/comments",
          ["POST", "PATCH", "DELETE"],
          ["/tasks/*/comments/*/"],
        ),
        write(
          "create_project",
          "Create project",
          "Create a project",
          "/projects",
          ["POST"],
        ),
        write(
          "update_project",
          "Update project",
          "Change a project's details or status",
          "/projects/*/",
          ["PATCH"],
        ),
        write(
          "delete_project",
          "Delete project",
          "Delete a project",
          "/projects/*/",
          ["DELETE"],
        ),
        write(
          "create_milestone",
          "Create milestone",
          "Create a milestone in a project",
          "/milestones",
          ["POST"],
        ),
        write(
          "update_milestone",
          "Update milestone",
          "Change a milestone's details",
          "/milestones/*/",
          ["PATCH"],
        ),
        write(
          "delete_milestone",
          "Delete milestone",
          "Delete a milestone",
          "/milestones/*/",
          ["DELETE"],
        ),
        // Feature requests
        write(
          "create_feature_request",
          "Create feature request",
          "Create a feature request",
          "/feature-requests",
          ["POST"],
        ),
        write(
          "update_feature_request",
          "Update feature request",
          "Change a feature request's details",
          "/feature-requests/*/",
          ["PATCH"],
        ),
        write(
          "link_feature_request_evidence",
          "Link feature request evidence",
          "Link a customer account to a feature request as evidence",
          "/feature-requests/*/evidence",
          ["POST"],
        ),
        write(
          "set_feature_request_portal_visibility",
          "Set feature request portal visibility",
          "Show or hide a feature request in the customer portal",
          "/feature-requests/*/set-portal-visibility",
          ["POST"],
        ),
        write(
          "delete_feature_request",
          "Delete feature request",
          "Delete a feature request",
          "/feature-requests/*/",
          ["DELETE"],
        ),
        write(
          "merge_feature_requests",
          "Merge feature requests",
          "Merge feature requests into one",
          "/feature-requests/merge",
          ["POST"],
        ),
        // Call recordings
        write(
          "update_call_recording",
          "Update call recording",
          "Change a call recording's details",
          "/call-recordings/*/",
          ["PATCH"],
        ),
        write(
          "delete_call_recording",
          "Delete call recording",
          "Delete a call recording",
          "/call-recordings/*/",
          ["DELETE"],
        ),
        // Custom fields and objects
        write(
          "manage_custom_fields",
          "Manage custom fields",
          "Create or change custom fields and their select options",
          "/custom-fields",
          ["POST", "PATCH", "DELETE"],
          ["/custom-fields/*/", "/custom-fields/*/select-options"],
        ),
        write(
          "create_custom_object",
          "Create custom object",
          "Create a custom object",
          "/custom-objects/*/",
          ["POST"],
        ),
        write(
          "update_custom_objects",
          "Update custom objects",
          "Change one custom object or several at once",
          "/custom-objects/*/*/",
          ["PATCH"],
          ["/custom-objects/*/"],
        ),
        write(
          "delete_custom_object",
          "Delete custom object",
          "Delete a custom object",
          "/custom-objects/*/*/",
          ["DELETE"],
        ),
        // Tags, macros, ticket forms, attachments
        write(
          "manage_tags",
          "Manage tags",
          "Create, rename, or delete tags",
          "/tags",
          ["POST", "PATCH", "DELETE"],
          ["/tags/*/"],
        ),
        write(
          "manage_macros",
          "Manage macros",
          "Create, change, or delete macros",
          "/macros",
          ["POST", "PATCH", "DELETE"],
          ["/macros/*/"],
        ),
        write(
          "submit_ticket_form",
          "Submit ticket form",
          "Submit a ticket form on a customer's behalf",
          "/ticket-forms/*/submissions",
          ["POST"],
        ),
        write(
          "create_attachment",
          "Create attachment",
          "Upload a file as an attachment",
          "/attachments",
          ["POST"],
        ),
        // Email and training data
        write(
          "delete_email_suppression",
          "Remove email suppression",
          "Remove a recipient from the email suppression list",
          "/email-suppressions/*/",
          ["DELETE"],
        ),
        write(
          "manage_training_data",
          "Manage training data",
          "Create AI training data configurations, upload content, or delete documents",
          "/training-data",
          ["POST", "DELETE"],
          [
            "/training-data/upload",
            "/training-data/upload-content",
            "/training-data/*/documents",
          ],
        ),
      ],
    },
  ],
};
