import type { AppPermissionDefinition } from "./types";

export const sentryPermissions: AppPermissionDefinition = {
  provider: "sentry",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_organizations",
          name: "List organizations",
          description: "List accessible organizations",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/organizations/",
          method: "GET",
        },
        {
          id: "get_organization",
          name: "Get organization",
          description: "Retrieve organization details",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/organizations/*",
          method: "GET",
        },
        {
          id: "list_projects",
          name: "List projects",
          description: "List projects in an organization",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/organizations/*/projects/",
          method: "GET",
        },
        {
          id: "get_project",
          name: "Get project",
          description: "Retrieve project details",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/projects/*/*",
          method: "GET",
        },
        {
          id: "list_issues",
          name: "List issues",
          description: "List issues in a project",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/projects/*/*/issues/",
          method: "GET",
        },
        {
          id: "get_issue",
          name: "Get issue",
          description: "Retrieve issue details",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/issues/*",
          method: "GET",
        },
        {
          id: "list_issue_events",
          name: "List issue events",
          description: "List events for an issue",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/issues/*/events/",
          method: "GET",
        },
        {
          id: "list_teams",
          name: "List teams",
          description: "List teams in an organization",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/organizations/*/teams/",
          method: "GET",
        },
        {
          id: "list_members",
          name: "List members",
          description: "List organization members",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/organizations/*/members/",
          method: "GET",
        },
        {
          id: "get_user",
          name: "Get current user",
          description: "Retrieve the authenticated user",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/users/me/",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "update_issue",
          name: "Update issue",
          description: "Resolve, archive, or update an issue",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/issues/*",
          method: "PUT",
        },
        {
          id: "delete_issue",
          name: "Delete issue",
          description: "Delete an issue",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/issues/*",
          method: "DELETE",
        },
        {
          id: "create_release",
          name: "Create release",
          description: "Create a new release",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/organizations/*/releases/",
          method: "POST",
        },
        {
          id: "create_deploy",
          name: "Create deploy",
          description: "Create a deploy for a release",
          hostPattern: "*.sentry.io",
          pathPattern: "/api/0/organizations/*/releases/*/deploys/",
          method: "POST",
        },
      ],
    },
  ],
};
