import type { AppPermissionDefinition } from "./types";

export const vercelPermissions: AppPermissionDefinition = {
  provider: "vercel",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_projects",
          name: "List projects",
          description: "List all projects",
          hostPattern: "api.vercel.com",
          pathPattern: "/v10/projects",
          method: "GET",
        },
        {
          id: "get_project",
          name: "Get project",
          description: "Get a specific project",
          hostPattern: "api.vercel.com",
          pathPattern: "/v9/projects/*",
          method: "GET",
        },
        {
          id: "list_deployments",
          name: "List deployments",
          description: "List deployments",
          hostPattern: "api.vercel.com",
          pathPattern: "/v7/deployments",
          method: "GET",
        },
        {
          id: "get_deployment",
          name: "Get deployment",
          description: "Get a specific deployment",
          hostPattern: "api.vercel.com",
          pathPattern: "/v13/deployments/*",
          method: "GET",
        },
        {
          id: "list_env_vars",
          name: "List env vars",
          description: "List environment variables for a project",
          hostPattern: "api.vercel.com",
          pathPattern: "/v10/projects/*/env",
          method: "GET",
        },
        {
          id: "list_domains",
          name: "List domains",
          description: "List all domains",
          hostPattern: "api.vercel.com",
          pathPattern: "/v5/domains",
          method: "GET",
        },
        {
          id: "get_user",
          name: "Get user",
          description: "Get the authenticated user",
          hostPattern: "api.vercel.com",
          pathPattern: "/v2/user",
          method: "GET",
        },
        {
          id: "list_teams",
          name: "List teams",
          description: "List teams",
          hostPattern: "api.vercel.com",
          pathPattern: "/v2/teams",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_deployment",
          name: "Create deployment",
          description: "Create a new deployment",
          hostPattern: "api.vercel.com",
          pathPattern: "/v13/deployments",
          method: "POST",
        },
        {
          id: "create_env_var",
          name: "Create env var",
          description: "Create an environment variable",
          hostPattern: "api.vercel.com",
          pathPattern: "/v10/projects/*/env",
          method: "POST",
        },
        {
          id: "update_env_var",
          name: "Update env var",
          description: "Update an environment variable",
          hostPattern: "api.vercel.com",
          pathPattern: "/v9/projects/*/env/*",
          method: "PATCH",
        },
        {
          id: "delete_env_var",
          name: "Delete env var",
          description: "Delete an environment variable",
          hostPattern: "api.vercel.com",
          pathPattern: "/v9/projects/*/env/*",
          method: "DELETE",
        },
        {
          id: "add_domain",
          name: "Add domain",
          description: "Add a domain",
          hostPattern: "api.vercel.com",
          pathPattern: "/v7/domains",
          method: "POST",
        },
        {
          id: "remove_domain",
          name: "Remove domain",
          description: "Remove a domain",
          hostPattern: "api.vercel.com",
          pathPattern: "/v6/domains/*",
          method: "DELETE",
        },
      ],
    },
  ],
};
