import type { AppPermissionDefinition } from "./types";

export const xPermissions: AppPermissionDefinition = {
  provider: "x",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "get_user",
          name: "Get user",
          description: "Retrieve a user profile",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*",
          method: "GET",
        },
        {
          id: "get_me",
          name: "Get current user",
          description: "Retrieve the authenticated user",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/me",
          method: "GET",
        },
        {
          id: "get_tweet",
          name: "Get post",
          description: "Retrieve a specific post",
          hostPattern: "api.x.com",
          pathPattern: "/2/tweets/*",
          method: "GET",
        },
        {
          id: "search_tweets",
          name: "Search posts",
          description: "Search recent posts",
          hostPattern: "api.x.com",
          pathPattern: "/2/tweets/search/recent",
          method: "GET",
        },
        {
          id: "get_timeline",
          name: "Get timeline",
          description: "Retrieve a user's timeline",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/tweets",
          method: "GET",
        },
        {
          id: "get_mentions",
          name: "Get mentions",
          description: "Retrieve a user's mentions",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/mentions",
          method: "GET",
        },
        {
          id: "list_followers",
          name: "List followers",
          description: "List a user's followers",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/followers",
          method: "GET",
        },
        {
          id: "list_following",
          name: "List following",
          description: "List accounts a user follows",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/following",
          method: "GET",
        },
        {
          id: "list_liked_tweets",
          name: "List liked posts",
          description: "List a user's liked posts",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/liked_tweets",
          method: "GET",
        },
        {
          id: "list_bookmarks",
          name: "List bookmarks",
          description: "List bookmarked posts",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/bookmarks",
          method: "GET",
        },
        {
          id: "list_dm_events",
          name: "List DM events",
          description: "List direct message events",
          hostPattern: "api.x.com",
          pathPattern: "/2/dm_events",
          method: "GET",
        },
        {
          id: "list_lists",
          name: "List lists",
          description: "List a user's lists",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/owned_lists",
          method: "GET",
        },
        {
          id: "list_blocks",
          name: "List blocks",
          description: "List blocked accounts",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/blocking",
          method: "GET",
        },
        {
          id: "list_mutes",
          name: "List mutes",
          description: "List muted accounts",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/muting",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_tweet",
          name: "Create post",
          description: "Create a new post",
          hostPattern: "api.x.com",
          pathPattern: "/2/tweets",
          method: "POST",
        },
        {
          id: "delete_tweet",
          name: "Delete post",
          description: "Delete a post",
          hostPattern: "api.x.com",
          pathPattern: "/2/tweets/*",
          method: "DELETE",
        },
        {
          id: "like_tweet",
          name: "Like post",
          description: "Like a post",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/likes",
          method: "POST",
        },
        {
          id: "unlike_tweet",
          name: "Unlike post",
          description: "Remove a like",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/likes/*",
          method: "DELETE",
        },
        {
          id: "retweet",
          name: "Repost",
          description: "Repost a post",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/retweets",
          method: "POST",
        },
        {
          id: "follow",
          name: "Follow",
          description: "Follow an account",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/following",
          method: "POST",
        },
        {
          id: "unfollow",
          name: "Unfollow",
          description: "Unfollow an account",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/following/*",
          method: "DELETE",
        },
        {
          id: "send_dm",
          name: "Send DM",
          description: "Send a direct message",
          hostPattern: "api.x.com",
          pathPattern: "/2/dm_conversations/*/messages",
          method: "POST",
        },
        {
          id: "create_bookmark",
          name: "Bookmark post",
          description: "Bookmark a post",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/bookmarks",
          method: "POST",
        },
        {
          id: "delete_bookmark",
          name: "Remove bookmark",
          description: "Remove a bookmark",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/bookmarks/*",
          method: "DELETE",
        },
        {
          id: "block_user",
          name: "Block",
          description: "Block an account",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/blocking",
          method: "POST",
        },
        {
          id: "mute_user",
          name: "Mute",
          description: "Mute an account",
          hostPattern: "api.x.com",
          pathPattern: "/2/users/*/muting",
          method: "POST",
        },
        {
          id: "upload_media",
          name: "Upload media",
          description: "Upload images or videos",
          hostPattern: "api.x.com",
          pathPattern: "/2/media/upload",
          method: "POST",
        },
        {
          id: "create_list",
          name: "Create list",
          description: "Create a new list",
          hostPattern: "api.x.com",
          pathPattern: "/2/lists",
          method: "POST",
        },
        {
          id: "hide_reply",
          name: "Hide reply",
          description: "Hide a reply to a post",
          hostPattern: "api.x.com",
          pathPattern: "/2/tweets/*/hidden",
          method: "PUT",
        },
      ],
    },
  ],
};
