import type { AppPermissionDefinition } from "./types";

export const zohoCrmPermissions: AppPermissionDefinition = {
  provider: "zoho-crm",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_leads",
          name: "List leads",
          description: "List CRM leads",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Leads",
          method: "GET",
        },
        {
          id: "get_lead",
          name: "Get lead",
          description: "Retrieve a specific lead",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Leads/*",
          method: "GET",
        },
        {
          id: "list_contacts",
          name: "List contacts",
          description: "List CRM contacts",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Contacts",
          method: "GET",
        },
        {
          id: "get_contact",
          name: "Get contact",
          description: "Retrieve a specific contact",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Contacts/*",
          method: "GET",
        },
        {
          id: "list_accounts",
          name: "List accounts",
          description: "List CRM accounts",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Accounts",
          method: "GET",
        },
        {
          id: "get_account",
          name: "Get account",
          description: "Retrieve a specific account",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Accounts/*",
          method: "GET",
        },
        {
          id: "list_deals",
          name: "List deals",
          description: "List CRM deals",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Deals",
          method: "GET",
        },
        {
          id: "get_deal",
          name: "Get deal",
          description: "Retrieve a specific deal",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Deals/*",
          method: "GET",
        },
        {
          id: "list_tasks",
          name: "List tasks",
          description: "List CRM tasks",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Tasks",
          method: "GET",
        },
        {
          id: "get_task",
          name: "Get task",
          description: "Retrieve a specific task",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Tasks/*",
          method: "GET",
        },
        {
          id: "list_users",
          name: "List users",
          description: "List CRM users",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/users",
          method: "GET",
        },
        {
          id: "get_settings",
          name: "Get settings",
          description: "View CRM settings",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/settings/*",
          method: "GET",
        },
        {
          id: "get_org",
          name: "Get organization",
          description: "View organization details",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/org",
          method: "GET",
        },
        {
          id: "search_records",
          name: "Search records",
          description: "Search CRM records using COQL",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/coql",
          method: "POST",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_lead",
          name: "Create lead",
          description: "Create a new lead",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Leads",
          method: "POST",
        },
        {
          id: "update_lead",
          name: "Update lead",
          description: "Update an existing lead",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Leads/*",
          method: "PUT",
        },
        {
          id: "delete_lead",
          name: "Delete lead",
          description: "Delete a lead",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Leads/*",
          method: "DELETE",
        },
        {
          id: "create_contact",
          name: "Create contact",
          description: "Create a new contact",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Contacts",
          method: "POST",
        },
        {
          id: "update_contact",
          name: "Update contact",
          description: "Update an existing contact",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Contacts/*",
          method: "PUT",
        },
        {
          id: "delete_contact",
          name: "Delete contact",
          description: "Delete a contact",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Contacts/*",
          method: "DELETE",
        },
        {
          id: "create_account",
          name: "Create account",
          description: "Create a new account",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Accounts",
          method: "POST",
        },
        {
          id: "update_account",
          name: "Update account",
          description: "Update an existing account",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Accounts/*",
          method: "PUT",
        },
        {
          id: "delete_account",
          name: "Delete account",
          description: "Delete an account",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Accounts/*",
          method: "DELETE",
        },
        {
          id: "create_deal",
          name: "Create deal",
          description: "Create a new deal",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Deals",
          method: "POST",
        },
        {
          id: "update_deal",
          name: "Update deal",
          description: "Update an existing deal",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Deals/*",
          method: "PUT",
        },
        {
          id: "delete_deal",
          name: "Delete deal",
          description: "Delete a deal",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Deals/*",
          method: "DELETE",
        },
        {
          id: "create_task",
          name: "Create task",
          description: "Create a new task",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Tasks",
          method: "POST",
        },
        {
          id: "update_task",
          name: "Update task",
          description: "Update an existing task",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Tasks/*",
          method: "PUT",
        },
        {
          id: "delete_task",
          name: "Delete task",
          description: "Delete a task",
          hostPattern: "www.zohoapis.com",
          pathPattern: "/crm/v8/Tasks/*",
          method: "DELETE",
        },
      ],
    },
  ],
};
