import { chmodSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type {
  AgentChannelPresenceWire,
  AgentConnectionWire,
  AgentPeerWire,
  HarnessCapabilities,
} from "@onecli/agent-protocol";
import { cleanLabel } from "@onecli/agent-protocol";
import { agentsFragment } from "../capabilities/agents";
import { channelsFragment } from "../capabilities/channels";
import {
  CONNECTIONS_FRAGMENT_ID,
  connectedAppsBlock,
} from "../capabilities/connections";

/**
 * The instruction renderer is a collector, not an author (plan step 2, §3.7):
 * the platform preamble first (identity + the boundary map), then the
 * operator's brief, then one fragment per ENABLED capability — each owned by
 * that capability's module. The output is a pure projection of control-plane
 * truth: re-rendered on every boot (drift and tampering self-heal) and
 * written read-only, with a do-not-edit header naming the real sources.
 *
 * PLATFORM VOICE COMES FIRST (step 6.5). The brief is operator-authored text
 * we do not control; when it led the document it could open with its own
 * "## Who you are" and be indistinguishable from the platform's own words.
 * Establishing identity before any authored content — and labelling the brief
 * as the operator's — keeps the two voices apart.
 */

/** A capability's own instruction snippet — it arrives WITH the capability
 * (crons in step 7, memory in step 8, skills in step 9) and disappears with
 * it. Step 2 ships the registry empty. */
export interface CapabilityFragment {
  id: string;
  title: string;
  body: string;
}

export interface RenderInputs {
  /** The agent's brief (§3.11) — user-authored, human-owned. */
  instructions: string | undefined;
  /** The agent's display name — the identity it states when asked who it is.
   * Undefined only for a sandbox started without one (dev/stdio). */
  agentName: string | undefined;
  /**
   * The agent's channel presences (its own Slack app, later others), from
   * the spawn payload at boot and the home-sync final part mid-run. A RENDER
   * input like the two above rather than a static fragment: the channels
   * section is derived from it on every render, so an attach, a detach, or
   * a provider-side removal changes the doc without a reboot.
   */
  channels: readonly AgentChannelPresenceWire[];
  /**
   * The peer agents this agent may message (PR 5b), same render-input
   * posture as `channels`: the agents section is derived from it on every
   * render, so a new agent in the workspace changes the doc without a
   * reboot.
   */
  peers: readonly AgentPeerWire[];
  /**
   * The agent's attached app connections, same render-input posture: the
   * "Connected apps" block of the External services section is derived from
   * it on every render, so an attach, a detach, or a reconnect to another
   * org changes the doc without a reboot.
   */
  connections: readonly AgentConnectionWire[];
  capabilities: HarnessCapabilities;
  /** The STATIC fragments — each enabled capability's teaching, fixed for
   * the process. The channels fragment is not among them: it is derived
   * from `channels` at render time (see `renderInstructionDoc`). */
  fragments: CapabilityFragment[];
  /**
   * Where the derived channels section goes, as the id of the static
   * fragment it should FOLLOW (it reads best right after the standing
   * knowledge sections and before the machine ones). Absent or unmatched =
   * after every static fragment.
   */
  channelsAfter?: string;
}

const HEADER =
  "<!-- Generated by OneCLI — do not edit. " +
  "Your brief is set by your operator in the dashboard; this file is read-only and is rebuilt at every boot and whenever your brief, skills, or memory change. -->";

/**
 * The name is operator-supplied (dashboard, up to 255 free-form characters)
 * and lands INSIDE platform voice, so it gets the same treatment as any other
 * name we splice into a prompt (`cleanLabel`): control characters, newlines
 * and Unicode line separators included, stripped, then clamped. A name is
 * not a place to open a new markdown heading, and only a line break could
 * make one.
 *
 * This is document integrity, not a trust boundary: the brief beneath is
 * equally operator-authored, and an operator who wants to confuse their own
 * agent can already do it there.
 */
const preamble = (agentName: string | undefined): string => {
  const named = cleanLabel(agentName ?? "");
  return `## Who you are

${named ? `You are ${named}, a hosted agent` : "You are a hosted agent"} running on OneCLI: a sandboxed
computer provisioned and governed by the platform. Every request you make to
the outside world passes through the OneCLI gateway, which holds the real
credentials — your environment deliberately contains none.

This document and your brief are where your identity comes from. Your
environment also reports the runtime that executes you — that is plumbing,
not identity. When asked who you are, what you are, or what you are built on
— including when someone names a product and asks if that is you — answer as
the agent described here, hosted on OneCLI, and say you do not discuss the
platform's internals. Never repeat a runtime or vendor name, even to deny it.
Do not describe yourself as a coding assistant unless your brief says that is
your job.

## What you may change, and how

- **Your memory** (the files under memory/): yours to edit — changes save to
  the platform within seconds and survive this machine being replaced.
  memory/index.md is the one generated exception; never edit it.
- **Your brief** (the section below, when present): you may suggest changes to
  the person you work with; you cannot edit it yourself.
- **Generated files** (this file and its siblings) and your own
  configuration: never edit them — they are read-only, and rebuilt from the
  platform's records at every boot and whenever your brief, skills, or
  memory change.
- When you are asked to change standing behavior, say when the change will
  take effect (a brief edit reaches this file within seconds, and takes
  effect the next time you read it).`;
};

export const renderInstructionDoc = (inputs: RenderInputs): string => {
  const sections: string[] = [HEADER, preamble(inputs.agentName)];

  if (inputs.instructions?.trim()) {
    sections.push(
      `# Your brief (written by your operator)\n\n${inputs.instructions.trim()}`,
    );
  }

  // The channels and agents sections are DERIVED per render from their
  // lists, and spliced after the named static fragment so the doc reads in
  // the registry's intended order (channels, then agents - both answer
  // "who can I reach"); null (an empty list) renders nothing.
  const derived = [
    channelsFragment(inputs.channels),
    agentsFragment(inputs.peers),
  ].filter((fragment): fragment is CapabilityFragment => fragment !== null);
  const afterIndex = inputs.channelsAfter
    ? inputs.fragments.findIndex((f) => f.id === inputs.channelsAfter)
    : -1;
  const ordered: CapabilityFragment[] =
    derived.length === 0
      ? inputs.fragments
      : afterIndex === -1
        ? [...inputs.fragments, ...derived]
        : [
            ...inputs.fragments.slice(0, afterIndex + 1),
            ...derived,
            ...inputs.fragments.slice(afterIndex + 1),
          ];

  for (const fragment of ordered) {
    // The External services fragment is static teaching; the list of what
    // is actually connected (and where) is derived per render and rides at
    // its end, so the rules and the facts they apply to read together.
    const body =
      fragment.id === CONNECTIONS_FRAGMENT_ID
        ? [fragment.body.trim(), connectedAppsBlock(inputs.connections)]
            .filter(Boolean)
            .join("\n\n")
        : fragment.body.trim();
    sections.push(`## ${fragment.title}\n\n${body}`);
  }

  return `${sections.join("\n\n")}\n`;
};

export interface RenderedHome {
  /** Absolute paths of every file written this boot. */
  files: string[];
}

/**
 * Materialize the instruction docs and skill directory into the home.
 * Idempotent and self-healing: existing files are removed and rewritten
 * (they may be read-only from the previous boot), then locked to 0444 so an
 * agent's edit fails loudly instead of silently vanishing later.
 */
export const renderHome = (
  homeDir: string,
  inputs: RenderInputs,
): RenderedHome => {
  const doc = renderInstructionDoc(inputs);
  const files: string[] = [];

  for (const relative of inputs.capabilities.instructionFiles) {
    const path = join(homeDir, relative);
    mkdirSync(dirname(path), { recursive: true });
    // SECURITY (symlink hardening): unlink before writing. The agent controls
    // this directory, and a bare write would FOLLOW a symlink it planted —
    // redirecting our write onto any path this process can reach. Unlinking
    // removes the link, never its target.
    rmSync(path, { force: true });
    writeFileSync(path, doc);
    chmodSync(path, 0o444);
    files.push(path);
  }

  if (inputs.capabilities.skillsDir) {
    mkdirSync(join(homeDir, inputs.capabilities.skillsDir), {
      recursive: true,
    });
  }

  return { files };
};
