import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync, statSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { EnvFile, expand, resolveEnv } from "./env-file.mjs";

const dir = () => mkdtempSync(join(tmpdir(), "env-file-test-"));
const file = (content) => {
  const p = join(dir(), ".env");
  writeFileSync(p, content);
  return p;
};
const load = (content, opts) => new EnvFile(file(content), opts);

// ── round-trip fidelity ─────────────────────────────────────────────────────

test("an untouched file round-trips byte-identically", () => {
  const content = [
    "# a comment",
    "",
    "export FOO=bar # inline",
    "QUOTED=\"hello world\"",
    "SINGLE='keep $LITERAL'",
    "WEIRD LINE THAT PARSES AS NOTHING",
    "URL=postgresql://u:p@h:5432/db#frag",
    "",
  ].join("\n");
  const env = new EnvFile(file(content));
  env.dirty = true; // force a write with zero edits
  env.save();
  assert.equal(readFileSync(env.path, "utf8"), content);
});

test("CRLF files keep their line endings", () => {
  const content = "A=1\r\nB=2\r\n";
  const env = new EnvFile(file(content));
  env.upsert("C", "3");
  env.save();
  const out = readFileSync(env.path, "utf8");
  assert.ok(out.includes("A=1\r\nB=2\r\n"));
  assert.ok(out.endsWith("C=3\r\n"));
});

test("a multi-line double-quoted value survives round-trip and reads whole", () => {
  const content = 'KEY="-----BEGIN\nline2\nline3-----"\nAFTER=1\n';
  const env = new EnvFile(file(content));
  assert.equal(env.get("KEY"), "-----BEGIN\nline2\nline3-----");
  assert.equal(env.get("AFTER"), "1");
  env.dirty = true;
  env.save();
  assert.equal(readFileSync(env.path, "utf8"), content);
});

// ── reads ───────────────────────────────────────────────────────────────────

test("last assignment wins and duplicates are reported", () => {
  const env = load("A=first\nB=x\nA=second\n");
  assert.equal(env.get("A"), "second");
  assert.deepEqual(env.duplicates(), ["A"]);
});

test("has() distinguishes present-empty from absent", () => {
  const env = load("EMPTY=\n");
  assert.equal(env.has("EMPTY"), true);
  assert.equal(env.get("EMPTY"), "");
  assert.equal(env.has("MISSING"), false);
  assert.equal(env.get("MISSING"), undefined);
});

test("quotes unwrap; double quotes cook \\n; whitespace around = tolerated", () => {
  const env = load('A="line1\\nline2"\nB = spaced\nC=\'raw\\n\'\n');
  assert.equal(env.get("A"), "line1\nline2");
  assert.equal(env.get("B"), "spaced");
  assert.equal(env.get("C"), "raw\\n");
});

test("unquoted values keep a glued # but drop a spaced # comment", () => {
  const env = load("URL=http://h/x#frag\nK=value # comment\n");
  assert.equal(env.get("URL"), "http://h/x#frag");
  assert.equal(env.get("K"), "value");
});

test("a value containing = splits on the first = only", () => {
  const env = load("JWT=abc=def==\n");
  assert.equal(env.get("JWT"), "abc=def==");
});

// ── upsert ──────────────────────────────────────────────────────────────────

test("upsert replaces in place, preserving export prefix, quotes and inline comment", () => {
  const env = load('# top\nexport TOKEN="old" # keep me\nAFTER=1\n');
  env.upsert("TOKEN", "new");
  env.save();
  assert.equal(
    readFileSync(env.path, "utf8"),
    '# top\nexport TOKEN="new" # keep me\nAFTER=1\n',
  );
});

test("upsert with the current value is a no-op", () => {
  const env = load("A=same\n");
  assert.equal(env.upsert("A", "same"), false);
  assert.equal(env.dirty, false);
});

test("upsert uncomments the last # KEY= stub instead of appending", () => {
  const env = load("# APP_URL=https://example.com\n# unrelated\n");
  env.upsert("APP_URL", "http://localhost:10254");
  env.save();
  const out = readFileSync(env.path, "utf8");
  assert.ok(out.startsWith("APP_URL=http://localhost:10254\n"));
  assert.ok(!out.includes("Generated by"));
});

test("upsert appends under one generated header, with comments, reusing it", () => {
  const env = load("EXISTING=1\n", { label: "pnpm dev" });
  env.upsert("A", "1", { comment: "first secret" });
  env.upsert("B", "2", { comment: "second secret" });
  env.save();
  const out = readFileSync(env.path, "utf8");
  const headers = out.match(/Generated by `pnpm dev`/g) ?? [];
  assert.equal(headers.length, 1);
  assert.ok(out.includes("# first secret\nA=1\n# second secret\nB=2\n"));

  // A later load + append finds the existing header rather than adding one.
  const again = new EnvFile(env.path, { label: "pnpm dev" });
  again.upsert("C", "3");
  again.save();
  const twice = readFileSync(env.path, "utf8").match(/Generated by `pnpm dev`/g);
  assert.equal(twice.length, 1);
});

test("a replacement value needing quoting gets double quotes", () => {
  const env = load("");
  env.upsert("MSG", "two words");
  env.save();
  assert.ok(readFileSync(env.path, "utf8").includes('MSG="two words"'));
});

test("replacing a multi-line value collapses it to one line", () => {
  const env = load('KEY="a\nb"\n');
  env.upsert("KEY", "x\ny");
  env.save();
  assert.equal(readFileSync(env.path, "utf8"), 'KEY="x\\ny"\n');
  assert.equal(new EnvFile(env.path).get("KEY"), "x\ny");
});

// ── save ────────────────────────────────────────────────────────────────────

test("save always asserts 0600 — new files and permissive existing ones alike", () => {
  const p = join(dir(), ".env");
  const env = new EnvFile(p);
  assert.equal(env.existed, false);
  env.upsert("A", "1");
  env.save();
  assert.equal(statSync(p).mode & 0o777, 0o600);

  // A hand-created world-readable file gets TIGHTENED once secrets land in
  // it, not respected — these files hold secrets by design.
  const p2 = join(dir(), ".env");
  writeFileSync(p2, "A=1\n", { mode: 0o644 });
  const env2 = new EnvFile(p2);
  env2.upsert("B", "2");
  env2.save();
  assert.equal(statSync(p2).mode & 0o777, 0o600);
});

test("save is a no-op when clean and leaves no tmp files behind", () => {
  const p = file("A=1\n");
  const env = new EnvFile(p);
  assert.equal(env.save(), false);
  env.upsert("B", "2");
  assert.equal(env.save(), true);
  const names = readdirSync(join(p, ".."));
  assert.deepEqual(
    names.filter((n) => n.includes(".tmp")),
    [],
  );
});

// ── hostile inputs ──────────────────────────────────────────────────────────

test("an unterminated quote does NOT swallow the rest of the file", () => {
  const env = load('BROKEN="oops\nDATABASE_URL=postgresql://real\nKEY=alive\n');
  // dotenv behavior: the broken line becomes a bare value, quote included…
  assert.equal(env.get("BROKEN"), '"oops');
  // …and every later key stays visible — nothing gets silently re-minted.
  assert.equal(env.get("DATABASE_URL"), "postgresql://real");
  assert.equal(env.get("KEY"), "alive");
  env.dirty = true;
  env.save();
  assert.equal(
    readFileSync(env.path, "utf8"),
    'BROKEN="oops\nDATABASE_URL=postgresql://real\nKEY=alive\n',
  );
});

test("a multi-line value closing mid-line keeps its tail and the next key", () => {
  const env = load('KEY="abc\ndef" # comment\nAFTER=1\n');
  assert.equal(env.get("KEY"), "abc\ndef");
  assert.equal(env.get("AFTER"), "1");
  env.dirty = true;
  env.save();
  assert.equal(
    readFileSync(env.path, "utf8"),
    'KEY="abc\ndef" # comment\nAFTER=1\n',
  );
});

test("values containing quotes round-trip through upsert (append and replace)", () => {
  const env = load('TOKEN="old"\n');
  env.upsert("TOKEN", 'ne"w');
  env.upsert("PW", 'pa"ss word');
  env.save();
  const again = new EnvFile(env.path);
  assert.equal(again.get("TOKEN"), 'ne"w');
  assert.equal(again.get("PW"), 'pa"ss word');
});

test("a file without a trailing newline appends cleanly", () => {
  const env = load("A=1");
  env.upsert("B", "2");
  env.save();
  const again = new EnvFile(env.path);
  assert.equal(again.get("A"), "1");
  assert.equal(again.get("B"), "2");
});

test("an export-prefixed stub uncomments with the prefix intact", () => {
  const env = load("# export APP_URL=https://old.example\n");
  env.upsert("APP_URL", "http://localhost:10254");
  env.save();
  assert.equal(
    readFileSync(env.path, "utf8"),
    "export APP_URL=http://localhost:10254\n",
  );
});

test("an unreadable existing file throws instead of being treated as absent", () => {
  const d = dir();
  const env = () => new EnvFile(d); // a DIRECTORY at the path → EISDIR
  assert.throws(env, /EISDIR|illegal operation/i);
});

// ── expansion + resolution ──────────────────────────────────────────────────

test("expand handles ${VAR}, $VAR, defaults and the \\$ escape", () => {
  const lookup = (n) => ({ SET: "v", EMPTY: "" })[n];
  assert.equal(expand("${SET}", lookup), "v");
  assert.equal(expand("$SET/x", lookup), "v/x");
  assert.equal(expand("${MISSING}", lookup), "");
  assert.equal(expand("${MISSING:-d}", lookup), "d");
  assert.equal(expand("${EMPTY:-d}", lookup), "d");
  assert.equal(expand("${EMPTY-d}", lookup), "");
  assert.equal(expand("${MISSING-d}", lookup), "d");
  assert.equal(expand("\\$SET", lookup), "$SET");
});

test("resolveEnv: file order expansion, single quotes literal, shell always wins", () => {
  const env = load(
    "EDITION=cloud\nNEXT_PUBLIC_EDITION=${EDITION}\nLITERAL='${EDITION}'\nHOME_REF=${FAKE_HOME}/x\nSHELL_BEATS=file\n",
  );
  const resolved = resolveEnv(env, {
    FAKE_HOME: "/home/u",
    SHELL_BEATS: "shell",
  });
  assert.equal(resolved.NEXT_PUBLIC_EDITION, "cloud");
  assert.equal(resolved.LITERAL, "${EDITION}");
  assert.equal(resolved.HOME_REF, "/home/u/x");
  assert.equal(resolved.SHELL_BEATS, "shell");
});

test("resolveEnv: a forward reference resolves to empty (pinned semantics)", () => {
  const env = load("TWIN=${LATER}\nLATER=defined\n");
  const resolved = resolveEnv(env, {});
  assert.equal(resolved.TWIN, "");
  assert.equal(resolved.LATER, "defined");
});

test("resolveEnv: a shell variable beats the file even inside expansions", () => {
  const env = load("EDITION=cloud\nTWIN=${EDITION}\n");
  const resolved = resolveEnv(env, { EDITION: "" });
  assert.equal(resolved.EDITION, "");
  assert.equal(resolved.TWIN, "");
});

// ── hintStub ────────────────────────────────────────────────────────────────

test("hintStub appends a commented stub that a later upsert un-comments", () => {
  const env = load("EXISTING=1\n");
  assert.equal(
    env.hintStub("ONECLI_EXTERNAL_URL", "http://localhost:10254", {
      comment: "The URL people open OneCLI at.",
    }),
    true,
  );
  assert.equal(env.get("ONECLI_EXTERNAL_URL"), undefined);
  // The upsert must adopt the stub in place, not append a duplicate.
  env.upsert("ONECLI_EXTERNAL_URL", "http://192.168.1.20:10254");
  assert.equal(env.get("ONECLI_EXTERNAL_URL"), "http://192.168.1.20:10254");
});

test("hintStub is a no-op when the key exists as an assignment or a stub", () => {
  const assigned = load("ONECLI_EXTERNAL_URL=http://x.example\n");
  assert.equal(assigned.hintStub("ONECLI_EXTERNAL_URL", "y"), false);

  const stubbed = load("# ONECLI_EXTERNAL_URL=http://x.example\n");
  assert.equal(stubbed.hintStub("ONECLI_EXTERNAL_URL", "y"), false);
});
