/**
 * Shared shell script fragments for install and migrate scripts.
 */

/**
 * POSIX shell block that authenticates via device auth flow.
 * Sets $ONECLI_API_KEY on success, exits on failure/timeout.
 */
export const deviceAuthBlock = (onecliUrl: string): string[] => [
  'ONECLI_API_KEY=""',
  'ONECLI_WORKSPACE_ID=""',
  "",
  "# ── Device authentication ──",
  'echo "  Authenticating with OneCLI..."',
  'echo ""',
  "",
  `RESPONSE=$(curl -fsSL -X POST "${onecliUrl}/v1/auth/cli/session" -H "Content-Type: application/json" 2>/dev/null)`,
  "",
  "# Parse JSON response (POSIX-compatible, no jq needed)",
  `CODE=$(echo "$RESPONSE" | grep -o '"code":"[^"]*"' | head -1 | cut -d'"' -f4)`,
  `AUTH_URL=$(echo "$RESPONSE" | grep -o '"auth_url":"[^"]*"' | head -1 | cut -d'"' -f4)`,
  "",
  'if [ -z "$CODE" ]; then',
  '  echo "  Failed to create auth session. Check your network connection."',
  "  exit 1",
  "fi",
  "",
  'echo "  Open this URL to authenticate:"',
  'echo ""',
  'echo "    $AUTH_URL"',
  'echo ""',
  'echo "  Waiting for confirmation..."',
  "",
  "# Try to open the URL automatically",
  "if command -v open >/dev/null 2>&1; then",
  '  open "$AUTH_URL" 2>/dev/null || true',
  "elif command -v xdg-open >/dev/null 2>&1; then",
  '  xdg-open "$AUTH_URL" 2>/dev/null || true',
  "fi",
  "",
  "# Poll every 2 seconds, timeout after 5 minutes",
  "ELAPSED=0",
  "while [ $ELAPSED -lt 300 ]; do",
  `  POLL=$(curl -fsSL "${onecliUrl}/v1/auth/cli/poll?code=$CODE" 2>/dev/null || echo '{"status":"error"}')`,
  `  STATUS=$(echo "$POLL" | grep -o '"status":"[^"]*"' | head -1 | cut -d'"' -f4)`,
  "",
  '  if [ "$STATUS" = "ok" ]; then',
  `    ONECLI_API_KEY=$(echo "$POLL" | grep -o '"api_key":"[^"]*"' | head -1 | cut -d'"' -f4)`,
  `    ONECLI_WORKSPACE_ID=$(echo "$POLL" | grep -o '"workspace_id":"[^"]*"' | head -1 | cut -d'"' -f4)`,
  '    echo "  Authenticated!"',
  "    break",
  '  elif [ "$STATUS" = "expired" ]; then',
  '    echo "  Session expired. Please try again."',
  "    exit 1",
  "  fi",
  "",
  "  sleep 2",
  "  ELAPSED=$((ELAPSED + 2))",
  "done",
  "",
  'if [ -z "$ONECLI_API_KEY" ]; then',
  '  echo "  Timed out waiting for authentication."',
  "  exit 1",
  "fi",
];
