mod ca;
mod connect;
mod inject;
mod proxy;

use std::path::{Path, PathBuf};

use anyhow::Result;
use clap::Parser;
use tracing::{info, warn};
use tracing_subscriber::EnvFilter;

use crate::ca::CertificateAuthority;
use crate::proxy::ProxyServer;

#[derive(Parser)]
#[command(
    name = "onecli-proxy",
    about = "OneCLI MITM proxy for credential injection"
)]
struct Cli {
    /// Port to listen on.
    #[arg(long, default_value = "10255")]
    port: u16,

    /// Data directory for CA certificates and persistent state.
    #[arg(long, default_value = default_data_dir())]
    data_dir: PathBuf,

    /// OneCLI web API base URL (for credential fetching).
    #[arg(long, default_value = "http://localhost:10254")]
    api_url: String,

    /// Path to the proxy–API shared secret file.
    /// The secret is used to authenticate credential requests to the web API.
    /// Can also be set via the PROXY_SECRET environment variable (takes precedence).
    #[arg(long, default_value = default_proxy_secret_file())]
    proxy_secret_file: PathBuf,
}

fn default_data_dir() -> &'static str {
    if cfg!(target_os = "linux") && Path::new("/app/data").exists() {
        "/app/data"
    } else {
        "~/.onecli"
    }
}

fn default_proxy_secret_file() -> &'static str {
    if cfg!(target_os = "linux") && Path::new("/app/data").exists() {
        "/app/data/proxy-secret"
    } else {
        "~/.onecli/proxy-secret"
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    // Install ring as the default rustls CryptoProvider (required by reqwest)
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("failed to install rustls CryptoProvider");

    // Initialize logging
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    let cli = Cli::parse();

    // Expand ~ in data dir
    let data_dir = expand_tilde(&cli.data_dir);

    info!(data_dir = %data_dir.display(), "starting onecli-proxy");

    // Load or generate CA
    let ca = CertificateAuthority::load_or_generate(&data_dir).await?;

    // Load proxy–API shared secret:
    // 1. PROXY_SECRET env var (cloud: injected from Secrets Manager)
    // 2. File on disk (OSS: generated by web API on startup)
    let proxy_secret = load_proxy_secret(&cli.proxy_secret_file);

    info!(
        port = cli.port,
        api_url = %cli.api_url,
        proxy_secret_loaded = proxy_secret.is_some(),
        "proxy ready"
    );

    // Start the proxy server (blocks forever)
    let server = ProxyServer::new(ca, cli.port, cli.api_url, proxy_secret);
    server.run().await
}

/// Load the proxy–API shared secret.
/// Checks `PROXY_SECRET` env var first (cloud), then reads from file (OSS).
/// Returns `None` if neither is available (credential fetching will be disabled).
fn load_proxy_secret(secret_file: &Path) -> Option<String> {
    // Cloud: env var takes precedence
    if let Ok(secret) = std::env::var("PROXY_SECRET") {
        let secret = secret.trim().to_string();
        if !secret.is_empty() {
            info!("loaded proxy secret from PROXY_SECRET env var");
            return Some(secret);
        }
    }

    // OSS: read from file
    let path = expand_tilde(secret_file);
    match std::fs::read_to_string(&path) {
        Ok(contents) => {
            let secret = contents.trim().to_string();
            if secret.is_empty() {
                warn!(path = %path.display(), "proxy secret file is empty");
                None
            } else {
                info!(path = %path.display(), "loaded proxy secret from file");
                Some(secret)
            }
        }
        Err(_) => {
            warn!(
                path = %path.display(),
                "proxy secret file not found — credential fetching will be unavailable until the web API generates it"
            );
            None
        }
    }
}

/// Expand `~` at the start of a path to the user's home directory.
fn expand_tilde(path: &Path) -> PathBuf {
    let s = path.to_string_lossy();
    if s.starts_with("~/") || s == "~" {
        if let Some(home) = std::env::var_os("HOME") {
            return PathBuf::from(home).join(s.strip_prefix("~/").unwrap_or(""));
        }
    }
    path.to_path_buf()
}
