import type { AppPermissionDefinition } from "./types";

export const mongodbAtlasPermissions: AppPermissionDefinition = {
  provider: "mongodb-atlas",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_orgs",
          name: "List organizations",
          description: "List organizations the service account belongs to",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/orgs",
          method: "GET",
        },
        {
          id: "list_projects",
          name: "List projects",
          description: "List projects in an organization",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups",
          method: "GET",
        },
        {
          id: "get_project",
          name: "Get project",
          description: "Get project details by ID",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*",
          method: "GET",
        },
        {
          id: "list_clusters",
          name: "List clusters",
          description: "List all clusters in a project",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/clusters",
          method: "GET",
        },
        {
          id: "get_cluster",
          name: "Get cluster",
          description: "Get cluster configuration and status",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/clusters/*",
          method: "GET",
        },
        {
          id: "list_db_users",
          name: "List database users",
          description: "List database users in a project",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/databaseUsers",
          method: "GET",
        },
        {
          id: "list_access_list",
          name: "List network access",
          description: "List IP access list entries for a project",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/accessList",
          method: "GET",
        },
        {
          id: "list_alerts",
          name: "List alert configurations",
          description: "List alert configurations for a project",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/alertConfigs",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_project",
          name: "Create project",
          description: "Create a new Atlas project",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups",
          method: "POST",
        },
        {
          id: "create_cluster",
          name: "Create cluster",
          description: "Create a new cluster in a project",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/clusters",
          method: "POST",
        },
        {
          id: "update_cluster",
          name: "Update cluster",
          description: "Modify cluster configuration",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/clusters/*",
          method: "PATCH",
        },
        {
          id: "delete_cluster",
          name: "Delete cluster",
          description: "Delete a cluster from a project",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/clusters/*",
          method: "DELETE",
        },
        {
          id: "create_db_user",
          name: "Create database user",
          description: "Create a new database user",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/databaseUsers",
          method: "POST",
        },
        {
          id: "update_db_user",
          name: "Update database user",
          description: "Update database user roles or password",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/databaseUsers/*/*",
          method: "PATCH",
        },
        {
          id: "delete_db_user",
          name: "Delete database user",
          description: "Remove a database user from a project",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/databaseUsers/*/*",
          method: "DELETE",
        },
        {
          id: "add_access_list",
          name: "Add network access",
          description: "Add an IP address to the project access list",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/accessList",
          method: "POST",
        },
        {
          id: "delete_access_list",
          name: "Remove network access",
          description: "Remove an IP address from the access list",
          hostPattern: "cloud.mongodb.com",
          pathPattern: "/api/atlas/v2/groups/*/accessList/*",
          method: "DELETE",
        },
      ],
    },
  ],
};
