import { existsSync, readFileSync } from "fs";
import {
  GATEWAY_CA_CERT,
  GATEWAY_CA_PEM_FILE,
  HOME,
  IS_CLOUD,
} from "@/lib/env";

/**
 * Gateway CA certificate loading.
 *
 * The gateway generates a self-signed CA on startup. Other parts of the app
 * need the CA PEM to serve it (`GET /api/gateway/ca`) or return it inline
 * (`GET /api/container-config`).
 *
 * - **Cloud**: Read from `GATEWAY_CA_CERT` env var (sourced from Secrets Manager).
 * - **OSS**: Read from file on disk (generated by the gateway at startup).
 */

const CA_PEM_FILE_DOCKER = "/app/data/gateway/ca.pem";
const CA_PEM_FILE_LOCAL = `${HOME}/.onecli/gateway/ca.pem`;

/**
 * Determine the CA PEM file path.
 * Matches the gateway's default: `/app/data/gateway/ca.pem` in Docker, `~/.onecli/gateway/ca.pem` locally.
 */
const getCaPemFilePath = (): string => {
  if (GATEWAY_CA_PEM_FILE) return GATEWAY_CA_PEM_FILE;
  return existsSync("/app/data") ? CA_PEM_FILE_DOCKER : CA_PEM_FILE_LOCAL;
};

/**
 * Load the CA certificate PEM content.
 * Returns null if the certificate is not available.
 */
export const loadCaCertificate = (): string | null => {
  const envCert = GATEWAY_CA_CERT.trim();
  if (envCert) return envCert;

  // Explicit file path override — works in any edition
  if (GATEWAY_CA_PEM_FILE) {
    try {
      const pem = readFileSync(GATEWAY_CA_PEM_FILE, "utf-8").trim();
      return pem || null;
    } catch {
      return null;
    }
  }

  if (IS_CLOUD) return null;

  const path = getCaPemFilePath();
  try {
    const pem = readFileSync(path, "utf-8").trim();
    return pem || null;
  } catch {
    return null;
  }
};
