import { existsSync, readFileSync } from "fs";

/**
 * Proxy CA certificate loading.
 *
 * The proxy generates a self-signed CA on startup. Other parts of the app
 * need the CA PEM to serve it (`GET /api/proxy/ca`) or return it inline
 * (`GET /api/container-config`).
 *
 * - **Cloud**: Read from `PROXY_CA_CERT` env var (sourced from Secrets Manager).
 * - **OSS**: Read from file on disk (generated by the proxy at startup).
 */

const CA_PEM_FILE_DOCKER = "/app/data/proxy/ca.pem";
const CA_PEM_FILE_LOCAL = `${process.env.HOME}/.onecli/proxy/ca.pem`;

const isCloud = process.env.NEXT_PUBLIC_EDITION === "cloud";

/**
 * Determine the CA PEM file path.
 * Matches the proxy's default: `/app/data/proxy/ca.pem` in Docker, `~/.onecli/proxy/ca.pem` locally.
 */
const getCaPemFilePath = (): string => {
  if (process.env.PROXY_CA_PEM_FILE) return process.env.PROXY_CA_PEM_FILE;
  return existsSync("/app/data") ? CA_PEM_FILE_DOCKER : CA_PEM_FILE_LOCAL;
};

/**
 * Load the CA certificate PEM content.
 * Returns null if the certificate is not available.
 */
export const loadCaCertificate = (): string | null => {
  const envCert = process.env.PROXY_CA_CERT?.trim();
  if (envCert) return envCert;

  if (isCloud) return null;

  const path = getCaPemFilePath();
  try {
    const pem = readFileSync(path, "utf-8").trim();
    return pem || null;
  } catch {
    return null;
  }
};
